<div id="titulos">
    <h2>Desembarque->Linha de Fundo</h2>
    <h3>Entrevista</h3>
    <h2><?=$this->porto['pto_nome'] ?></h2>
</div>

<div class="esquerda-entrevista">
    <form action="<?=$this->url(array("controller"=>"linha-fundo","action"=>"atualizar"),null,true)?>" name="entrevista" onSubmit="return verificaData()">
        <fieldset id="Entrevista">
            
            <div class="esquerda">
                <div class="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" disabled="true" value="<?= $this->monitoramento['fd_id'] ?>" /><br />
                </div>
                <div class="form-esq">
                    <label>ID monitoramento:</label>
                    <input type="text" name="id_monitoramento" placeholder="ID"  value="<?= $this->monitoramento['mnt_id'] ?>" /><br />
                </div>
                <div class="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" placeholder = "ID" name="id_entrevista" disabled="true" value="<?= $this->entrevista['lf_id'] ?>"/><br />
                </div>
            </div>
            <br/>
            <div class="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div class="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox"  name="embarcada" <?php if($this->entrevista['lf_embarcada'] === true){ echo 'checked';} else{ echo '';}?>/><br />
                </div>
                <div class="form-esq">
                    <label>Motor?</label>
                    <input type="checkbox"  name="motor"  <?php if($this->entrevista['lf_motor'] === true){ echo 'checked';} else{ echo '';}?>/><br />
                </div>
                <div class="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco" placeholder="Nome do Barco" />
                    <option value=" " selected></option>
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>" <?=( $barco['bar_id'] == $this->entrevista['bar_id'])? 'selected="selected"': '';?>><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div class="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" />
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>" <?=( $tipoEmbarcacao['tte_id'] == $this->entrevista['tte_id'])? 'selected="selected"': '';?>><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>

            </div>
            <br/>
            <div class="direita-entrevista">
                <div class="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="pescadorEntrevistado" />
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>" <?=( $pescador['tp_id'] == $this->entrevista['tp_id_entrevistado'])? 'selected="selected"': '';?>><?= $pescador['tp_nome'] .' ( '. $pescador['tp_apelido']. ' )' ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div class="form-esq">
                    <label>Quant. de Pescadores:</label>
                    <input type="number" name="numPescadores" min="1" placeholder="QuantidadePescadores" value="<?=$this->entrevista['lf_quantpescadores']?>"/><br />
                </div>
            </div>
            <div class="esquerda">
                <legend><h4>Saída e Volta:</h4></legend>
                <div class="form-esq">

                    <label>Data:</label>
                    <input type="date" name="dataSaida" min="2013-11-01"  max = "<?= date("Y-m-d"); ?>" placeholder="Data da Saída" value="<?=$this->dataSaida?>"/>
                </div>
                <div class="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaSaida" placeholder="Hora da Saída" value="<?=$this->horaSaida?>"/>
                </div>
            </div>
            <div class="direita-entrevista">
                <div class="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataVolta" min="2013-11-01"  max = "<?= date("Y-m-d"); ?>" placeholder="Data da Volta" value="<?=$this->dataVolta?>"/>
                </div>
                <div class="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaVolta" placeholder="Hora da Volta" value="<?=$this->horaVolta?>"/>
                </div>
            </div>
            <br/>
            <div class="esquerda">
                <div class="form-esq">
                    <label>Tempo Gasto:</label>
                    <input type="time" name="tempoGasto" placeholder="Data da Saída" value="<?=$this->entrevista['lf_tempogasto']?>"/>
                </div>
            </div>
            <br/>
            <div class="esquerda">
                <div class="form-esq">
                    <legend><h4>Gastos:</h4></legend>
                    <label>Diesel(L):</label>
                    <input type="text"  name="diesel" placeholder="Diesel" value="<?=$this->entrevista['lf_diesel']?>"/>
                </div>
                <div class="form-dir">    
                    <label>Óleo(L):</label>
                    <input type="text"  name="oleo" placeholder="Óleo" value="<?=$this->entrevista['lf_oleo']?>"/><br />
                </div>
            </div>
            <div class="direita-entrevista">
                <div class="form-dir">    
                    <label>Alimento($):</label>
                    <input type="text"  name="alimento" placeholder="Alimento" value="<?=$this->entrevista['lf_alimento']?>"/><br />
                </div>
                <div class="form-dir">    
                    <label>Gelo($):</label>
                    <input type="text"  name="gelo" placeholder="Gelo" value="<?=$this->entrevista['lf_gelo']?>"/><br />
                </div>
            </div>
            <br/>
            <div class="esquerda">
                <div class="form-esq">
                    <legend><h4>Maré:</h4></legend>
                    <label>Tipo:</label>
                    <select name="mare" >
                        <?php
                        foreach ($this->mare as $key => $mare):
                            ?>
                            <option value="<?= $mare['mre_id'] ?>" <?=( $mare['mre_id'] == $this->entrevista['mre_id'])? 'selected="selected"': '';?>><?= $mare['mre_tipo'] ?></option>
                            <?php
                        endforeach;
                        ?>
                    </select>
                </div>
                <div class="form-dir">    
                    <label>Maré Viva?</label>
                    <input type="checkbox" name="mareviva" <?php if($this->entrevista['lf_mreviva'] === true){ echo 'checked';} else{ echo '';}?>> 
                </div>
            </div><br/>
            <div class="esquerda">
                <div class="form-esq">
                    <legend><h4>Esforço:</h4></legend>
                    <label>Número de Linhas:</label>
                    <input type="text" name="numLinhas" placeholder="Linhas" value="<?= $this->entrevista['lf_numlinhas']?>"/>
                </div>
                <div class="form-dir">    
                    <label> Anzóis p/ Linha:</label>
                    <input type="text" name="numAnzois" placeholder="Anzóis P/ Linha" value="<?= $this->entrevista['lf_numanzoisplinha']?>"/><br />
                </div>
            </div>
            <div class="direita-entrevista">
                <div class="form-esq">    
                    <label>Isca:</label>
                    <select name="isca" />
                    <?php
                    foreach ($this->iscas as $key => $isca):
                        ?>
                        <option value="<?= $isca['isc_id'] ?>"<?=( $isca['isc_id'] == $this->entrevista['isc_id'])? 'selected="selected"': '';?>><?= $isca['isc_tipo'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
            </div><br/>
            <div class="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div class="form-esq">    
                    <label>Destino do Pescado:</label>
                    <select name="destinoPescado" />
                    <?php
                    foreach ($this->destinos as $key => $destino):
                        ?>
                        <option value="<?= $destino['dp_id'] ?>" <?=( $destino['dp_id'] == $this->entrevista['dp_id'])? 'selected="selected"': '';?>><?= $destino['dp_destino'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                </div>
                
                <div class="form-esq">
                    <label for="tipo">Observacao:</label>
                    <input type="text" name="observacao" placeholder="Observação" value="<?=$this->entrevista['lf_obs']?>"/><br />
                </div>
                <input type="hidden" placeholder = "ID" name="id_entrevista"  value="<?= $this->entrevista['lf_id'] ?>"/><br />
                <input type="hidden" name="id_fichaDiaria" value="<?= $this->monitoramento['fd_id'] ?>" /><br />
                
                <div class="Submit">
                    <input type="submit" value="Salvar Alterações"/>
                </div>
            </div>      
        </fieldset>
    </form>
</div>  
    <form id="formEntrevistas">
       <input type="hidden" placeholder = "ID" name="id_entrevista"  value="<?= $this->entrevista['lf_id'] ?>"/><br />
        <input type="hidden" name="id_monitoramento" placeholder="ID"  value="<?= $this->entrevista['mnt_id'] ?>" /><br />
        <input type="hidden" name="id_fichaDiaria" placeholder="ID"  value="<?= $this->monitoramento['fd_id'] ?>" /><br />
       
        <fieldset class="noEditable"><legend>Pesqueiro:</legend>
                <fieldset class="noEditable"><legend>Pesqueiro e tempo até o pesqueiro:</legend>
                    <div id="base">
                        <input name="AddPesqueiro" onclick="ajax_pesqueiro(this.form, '<?= $this->url(array("controller" => "linha-fundo", "action" => "insertpesqueiro"), null, true) ?>', '<?= $this->entrevista['lf_id'] ?>', 'distancia')" type="button" value="Adicionar" />
                        <select style="float:left;" name="nomePesqueiro">
                            <?php foreach ($this->pesqueiros as $key => $pesqueiro): ?>
                                <option value="<?= $pesqueiro['paf_id']; ?>"><?= $pesqueiro['paf_pesqueiro']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <input style="float:left;" type="time" name="tempoAPesqueiro" placeholder="Tempo Até pesqueiro" size="10px"/>
                        <input style="float:left;" type="number" name="distAPesqueiro" placeholder="Distância Até pesqueiro (km)" size="23px"/>

                    </div>

                </fieldset>
                <br>
                <?php include('tablepesqueiro.phtml'); ?>
            </fieldset>
        <br /><br />
<fieldset class="noEditable"><legend>Espécies Capturadas:</legend>
        <fieldset class="noEditable"><legend>Dados das Espécies Capturadas:</legend>

            <div>
                <input readonly="" type="hidden" name="idRelacao" />
                <input class="responsivo" name="Add" onclick="ajax_select_peso_permitido(this.form, '<?= $this->url(array("controller" => "linha-fundo", "action" => "insertespeciecapturada"), null, true) ?>', <?= $this->entrevista['lf_id'] ?>, 'venda','<?= $this->url(array("controller" => "linha-fundo", "action" => "verificaespecie"), null, true) ?>')" type="button" value="Adicionar" />
                <select class="responsivo-esp" name="selectEspecie">
                    <?php foreach ($this->especies as $key => $especie): ?>
                        <option value="<?= $especie['esp_id']; ?>"><?= $especie['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <input class="responsivo-esp" type="text" name="quantidade" placeholder="Quantidade" size="10px">
                <input class="responsivo-esp" type="text" name="peso" placeholder="Peso" size="10px">
                <input class="responsivo-esp" type="text" name="precokg" placeholder="Preço por kg" size="10px">
                <select class="responsivo-esp" name="tipoVenda" class="espc">
                     <?php foreach ($this->tipovenda as $key => $tipovenda): ?>
                        <option value="<?= $tipovenda['ttv_id']?>"><?= $tipovenda['ttv_tipovenda']; ?></option>
                     <?php endforeach; ?>
                </select>

                <input type="hidden" name="id_entrevista"  value="<?= $this->entrevista['lf_id'] ?>"/>
                <?php include('mediaespecies.phtml'); ?>
            </div>

        </fieldset>
        <br>
         <?php include('tableespcaptura.phtml'); ?>
    </fieldset>
        <br /><br />
    <fieldset class="noEditable"><legend>Avistamento:</legend>
        <fieldset class="noEditable"><legend>O Que foi avistado:</legend>
            <div id="base">
                <input onclick="ajax_avistamento(this.form, '<?= $this->url(array("controller" => "linha-fundo", "action" => "insertavistamento"), null, true) ?>', '<?=$this->entrevista['lf_id']?>')" type="button" value="Adicionar" />
                
                <select style="float:left;" name="SelectAvistamento">
                    <?php foreach ($this->avistamentos as $key => $avistamento): ?>
                        <option value="<?= $avistamento['avs_id']; ?>"><?= $avistamento['avs_descricao']; ?></option>
                    <?php endforeach; ?>
                </select>
                
            </div>

        </fieldset>
        <br>
        <?php include('tableavistamento.phtml'); ?>
    </fieldset>
        <br /><br />
    <!--////////////////////////////////////////////////////////AMOSTRAGEM PEIXES///////////////////////////////////////////////////////////-->
    <fieldset class="noEditable"><legend>Amostras de Peixes:</legend>
        <fieldset class="noEditable"><legend>Dados das Amostras:</legend>

            <div id="base_peixe">
                <input type="hidden" readonly="" name="idRelacaoBioPeixe"/>
                <input class="responsivo" name="AddBioPeixe" onclick="ajax_biopeixe(this.form, '<?= $this->url(array("controller" => "linha-fundo", "action" => "insertbiopeixe"), null, true) ?>','<?=$this->entrevista['lf_id']?>')" type="button" value="Adicionar" />        
                <select style="float:left;" name="SelectEspeciePeixe">
                    <?php foreach ($this->especies as $key => $especie): ?>
                        <option value="<?= $especie['esp_id']; ?>"><?= $especie['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <input style="float:left;" type="text" name="comprimentoPeixe" placeholder="Comprimento (cm)" size="10px">

                <select style="float:left;" class="amostragem" name="SelectSexoPeixe" style="width:5px">
                    <option value="M">Macho</option>
                    <option value="F">Fêmea</option>
                    <option value="I">Indefinido</option>
                </select>
                
                <input style="float:left;" type="text" name="pesoPeixe" placeholder="Peso (kg)" size="10px">

                
            </div>

        </fieldset>
        <br>
         <?php include('tablebiopeixe.phtml'); ?>
        </fieldset>
        <br /><br />
<!--////////////////////////////////////////////////////////AMOSTRAGEM PEIXES///////////////////////////////////////////////////////////-->
        <fieldset class="noEditable"><legend>Amostras de Camarão:</legend>
        <fieldset class="noEditable"><legend>Dados das Amostras:</legend>

            <div id="base_camarao">
                <input type="hidden" readonly="" name="idRelacaoBioCamarao"/>
                <input class="responsivo" name="AddBioCamarao" onclick="ajax_biocamarao(this.form, '<?= $this->url(array("controller" => "linha-fundo", "action" => "insertbiocamarao"), null, true) ?>','<?=$this->entrevista['lf_id']?>')" type="button" value="Adicionar" />
                
                <select style="float:left;" name="SelectEspecieCamarao">
                    <?php foreach ($this->especieCamarao as $key => $especieCamarao): ?>
                        <option value="<?= $especieCamarao['esp_id']; ?>"><?= $especieCamarao['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <select style="float:left;" class="amostragem" name="SelectSexoCamarao" >
                    <option value="M">Macho</option>
                    <option value="F">Fêmea</option>
                    <option value="I">Indefinido</option>
                </select>
                <select style="float:left;" class="amostragem" name="SelectMaturidade">
                    <?php foreach ($this->maturidade as $key => $maturidade): ?>
                        <option value="<?= $maturidade['tmat_id']; ?>"><?= $maturidade['tmat_tipo']; ?></option>
                    <?php endforeach; ?>
                </select>
                
                <input style="float:left;" type="text" name="comprimentoCabeca" placeholder="Comp. Carapaça (mm)" size="10px">

                <input style="float:left;" type="text" name="pesoCamarao" placeholder="Peso (g)" size="10px">


            </div>

        </fieldset>
        <br>
        <?php include('tablebiocamarao.phtml'); ?>
</fieldset>    
</form>
    <br/> <br/>
    <a href="<?= $this->url(array("controller" => "ficha-diaria", "action" => "editar","id" => $this->monitoramento['fd_id']), null, true) ?>" id="botao-ancora">Voltar à Ficha-Diária</a>
    
