<fieldset id="Entrevista"></fieldset>
<form name="linha-fundo" method="post">

    <h2>Entrevistas Cadastradas->Pesca de Linha de Fundo (lista limitada em 200)</h2>

    <input type="button" class="busca" value="Limpar" onClick="jsClearBusca('<?= $this->url(array("controller" => "linha-fundo", "action" => "visualizar"), null, true) ?>')"/>
    <input type="button" class="busca" value="Buscar" onClick="jsBuscaEntrevistas(this.form, '<?= $this->url(array("controller" => "linha-fundo", "action" => "visualizar"), null, true) ?>')"/>
    <select class="busca" name="tipoBusca">
        <option value="1">Por ID</option>
        <option value="2">Por Pescador</option>
        <option value="3">Por Barco</option>
        <option value="4">Por Apelido</option>
        <option value="6">Listar Todas</option>
    </select>
    <input class="busca" name="buscaEntrevistas" placeholder="Buscar Entrevista"/><br/>
    <table id="dataTable" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
            <th>Entrevista</th>
            <th>Ficha Diária</th>
            <th>Monitoramento</th>
            <th>Pescador</th>
            <th>Apelido</th>
            <th>Barco</th>
            <th></th>
            <th></th>
            </tr>
        </thead>
        <tbody>

            <?php 
            foreach ($this->dados as $key => $entrevista): ?>
                <tr>
                <td><?= $entrevista['lf_id'] ?></td>
                <td><?= $entrevista['fd_id'] ?></td>
                <td><?= $entrevista['mnt_id'] ?></td>
                <td><?= $entrevista['tp_nome'] ?></td>
                <td><?= $entrevista['tp_apelido'] ?></td>
                <td><?= $entrevista['bar_nome'] ?></td>

                <td>
                    <a href="<?= $this->url(array("controller" => "linha-fundo", "action" => "editar", "id" => $entrevista['lf_id']), null, true) ?>">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a>
                </td>

                <td>
                    <a name="Excluir" class="button-del" onclick="beforeDelete('<?= $this->url(array("controller" => "linha-fundo", "action" => "excluir", "id" => $entrevista['lf_id']), null, true) ?>')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <br/><br/>
    <a href="<?= $this->url(array("controller" => "pescador", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
</form>
</html>
