<h2>Pescador Especialista -> Associação de Pesca</h2>
<form method="post">
<fieldset id="Especialista"></fieldset>

    <a id="ancora_associacao-pesca"></a>
    <fieldset class="noEditable"><legend>Associação de Pesca:</legend>
        <fieldset class="noEditable"><legend>Adicionar Associação de Pesca:</legend>
            <div id="base">
                <input type="button" name="Add" class="button-confirm" onclick="jsInsertDynamic(this.form, '<?= $this->url(array("controller" => "associacao-pesca", "action" => "insert"), null, true) ?>', '<?= $this->url(array("controller" => "associacao-pesca", "action" => "update"), null, true) ?>')">
                <input type="button" name="Reload" class="button-clear" onclick="jsReloadDynamic(this.form)">

                <input type="text" name="input_valor" placeholder="Associação de Pesca" size="40"  />
                <input readonly="" type="text" name="input_id" />
            </div>
        </fieldset>
        <br>

        <table id="tblPerfil">
            <tr>
                <th width="15%">ID </th>
                <th width="65%">Associação de Pesca</th>
                <th width="5%"></th>
                <th width="5%"></th>
            </tr>
            <?php foreach ($this->assignAssociacaoPesca as $key => $dadosAssociacaoPesca): ?>
                <tr id="rowNumPeril<?= $key ?>">
                    <td><?= $dadosAssociacaoPesca['tasp_id'] ?></td>
                    <td><?= $dadosAssociacaoPesca['tasp_associacao'] ?></td>
                    <td><input type="button" class="button-edit" width="5%" onclick="jsUpdateDynamic('<?= $dadosAssociacaoPesca['tasp_id'] ?>', '<?= $dadosAssociacaoPesca['tasp_associacao'] ?>', this.form)"></td>
                    <td><input type="button" class="button-del" width="5%" onclick="jsDeleteDynamic(<?= $dadosAssociacaoPesca['tasp_id'] ?>, '<?= $this->url(array("controller" => "associacao-pesca", "action" => "delete"), null, true) ?>')"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
    <fieldset class="noBorder">
        <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
        <a href="<?= $this->url(array("controller" => "associacao-pesca", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório - Lista</a>
    </fieldset>
</form>