<h2>Instituições</h2>
<h4>Universidade Estadual de Santa Cruz – UESC</h4>
<p>
A UESC, universidade pública do estado da Bahia, situa-se no sudeste da Bahia, município de Ilhéus e tem sua abrangência de atuação desde o Recôncavo Baiano ao extremo sul do Estado. 
Construindo conhecimento e competências mediante a oferta de 44 cursos de graduação, 17 cursos de mestrados e 03 cursos de doutorado. 
Consolidando-se assim, como uma instituição de ensino, pesquisa e extensão que contribui amplamente para o desenvolvimento de sua área de inserção. 
</p>

<h4>Bahia Mineração – BAMIN</h4>
<p>
A BAMIN é uma empresa nacional de extração de minério de ferro, responsável pelo Projeto Pedra de Ferro na região de Caetité que produzirá aproximadamente 20 milhões de toneladas de minério de ferro por ano. 
Toda a produção mineral será escoada para o terminal privativo de embarque pela Ferrovia de Integração Oeste-Leste, que vai ligar o município de Figueirópolis, em Tocantins a Ilhéus, litoral sul do estado da Bahia.
</p>

<h4>Instituto Superior de Sustentabilidade – ISUS</h4>
<p>
O ISUS é uma entidade que atua na área de modelagem e gestão de programas socioambientais. 
Mediante a utilização de ferramentas e estratégias modernas de gestão e inovação, visa ampliar os benefícios para a sociedade mediante a geração de emprego, a melhoria na qualidade de vida, o resgate da cidadania e a valorização dos patrimônios naturais e culturais relacionados ao desenvolvimento sustentável. 
</p>