<h2> Equipe</h2>
<h4>COORDENAÇÃO GERAL:</h4>
<p>Fernanda Jordão Guimarães - Doutora em Ciências Biológicas</p>
<br/>

<h4>COORDENAÇÃO DAS LINHAS DE AÇÃO:</h4>
<p><b>Perfil Social:</b> Carla Luisa Burda – Mestre em Sistemas Aquáticos Tropicais</p>
<p><b>Tráfego de Embarcações:</b> Daniela Alarcon – Doutoranda em Desenvolvimento e Meio Ambiente</p>
<p><b>Controle de Desembarque:</b> Débora Bluhu – Especialista em Planejamento Ambiental</p>
<p><b>Banco de Dados:</b> Marcelo Honda – Doutor na área de Ciências da Computação.</p>

