<h2>Porto -> Amendoeira</h2>

<script src="js/Chart.min.js"></script>

<script type="text/javascript">

    var options = {
        responsive:true,
        scaleOverride: false

    };
    var optionsCaptura = {
        responsive:true,
        scaleOverride: true,
	scaleStartValue: 0,
	scaleSteps: 15,
	scaleStepWidth: 1000
    };
    var responsive_false = {
        responsive:false
    };
    
   var entrevistasByMes = {
       labels: <?= $this->quantLabelsCalao ?>,
       datasets: [
           {
               label: "Quantidade de Entrevistas Por Mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantEntrevistasCalao ?>
           }
       ]
   };
   var capturaByMes = {
       labels: <?= $this->countCaptLabelsCalao ?>,
       datasets: [
           {
               label: "Captura total por mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->countCaptPesoCalao ?>
           }
       ]
   };
   var Embarcacoes = {
       labels: <?= $this->labelBarcosCalao ?>,
       datasets: [
           {
               label: "Barcos Mais Monitorados",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantBarcosCalao ?>
           }
       ]
   };
   
//   var datacapturaQuant = {
//       labels: <?= $this->arrayArtesQuant ?>,
//       datasets: [
//           {
//               label: "Quantidade",
//               fillColor: "rgba(95,48,43,.8)",
//               strokeColor: "rgba(95,48,43,1)",
//               pointColor: "rgba(95,48,43,1)",
//               pointStrokeColor: "#fff",
//               pointHighlightFill: "#fff",
//               pointHighlightStroke: "rgba(95,48,43,1)",
//               data: <?= $this->arrayQuant ?>
//           }
//       ]
//   };
//   
//   var databarcos = {
//       labels: <?= $this->arrayArtes ?>,
//       datasets: [
//           {
//               label: "Quantidade",
//               fillColor: "rgba(95,48,43,.8)",
//               strokeColor: "rgba(95,48,43,1)",
//               pointColor: "rgba(95,48,43,1)",
//               pointStrokeColor: "#fff",
//               pointHighlightFill: "#fff",
//               pointHighlightStroke: "rgba(95,48,43,1)",
//               data: <?= $this->arrayCount ?>
//           }
//       ]
//   };
//   var datapescador = {
//       labels: <?= $this->arrayArtes ?>,
//       datasets: [
//           {
//               label: "Quantidade",
//               fillColor: "rgba(95,48,43,.8)",
//               strokeColor: "rgba(95,48,43,1)",
//               pointColor: "rgba(95,48,43,1)",
//               pointStrokeColor: "#fff",
//               pointHighlightFill: "#fff",
//               pointHighlightStroke: "rgba(95,48,43,1)",
//               data: <?= $this->arrayCountPescador ?>
//           }
//       ]
//   };
//   var dataquantbarcos = {
//       labels: <?= $this->labelBarcos ?>,
//       datasets: [
//           {
//               label: "Quantidade",
//               fillColor: "rgba(95,48,43,.8)",
//               strokeColor: "rgba(95,48,43,1)",
//               pointColor: "rgba(95,48,43,1)",
//               pointStrokeColor: "#fff",
//               pointHighlightFill: "#fff",
//               pointHighlightStroke: "rgba(95,48,43,1)",
//               data: <?= $this->quantBarcos ?>
//           }
//       ]
//   };
//   
//   var dataquantpescadores = {
//       labels: <?= $this->labelPescadores ?>,
//       datasets: [
//           {
//               label: "Quantidade",
//               fillColor: "rgba(95,48,43,.8)",
//               strokeColor: "rgba(95,48,43,1)",
//               pointColor: "rgba(95,48,43,1)",
//               pointStrokeColor: "#fff",
//               pointHighlightFill: "#fff",
//               pointHighlightStroke: "rgba(95,48,43,1)",
//               data: <?= $this->quantPescadores ?>
//           }
//       ]
//   };
//   var dataquantcaptura = {
//       labels: <?= $this->labelCaptura ?>,
//       datasets: [
//           {
//               label: "Quantidade",
//               fillColor: "rgba(95,48,43,.8)",
//               strokeColor: "rgba(95,48,43,1)",
//               pointColor: "rgba(95,48,43,1)",
//               pointStrokeColor: "#fff",
//               pointHighlightFill: "#fff",
//               pointHighlightStroke: "rgba(95,48,43,1)",
//               data: <?= $this->quantCaptura ?>
//           }
//       ]
//   };
    
    window.onload = function(){
        
        var ctx = document.getElementById("EntrevistasByMes").getContext("2d");
        var EntrevistasChart = new Chart(ctx).Bar(entrevistasByMes, options);
        
        var ctx = document.getElementById("CapturaByMes").getContext("2d");
        var CapturaChart = new Chart(ctx).Bar(capturaByMes, options);

        var ctx = document.getElementById("BarcosMonitorados").getContext("2d");
        var EmbarcacoesCharts = new Chart(ctx).Bar(Embarcacoes, options);
//
//        var id_barcos = document.getElementById("Barcos").getContext("2d");
//        var BarChart = new Chart(id_barcos).Bar(databarcos, options);
//
//        var id_pesc = document.getElementById("Pescadores").getContext("2d");
//        var PescChart = new Chart(id_pesc).Bar(datapescador, options);
//
//        var id_quant_barcos = document.getElementById("QuantBarcos").getContext("2d");
//        var QuantBarChart = new Chart(id_quant_barcos).Bar(dataquantbarcos, options);
//
//        var id_quant_pesc = document.getElementById("QuantPescadores").getContext("2d");
//        var QuantPescChart = new Chart(id_quant_pesc).Bar(dataquantpescadores, options);
//        
//        var id_quant_capt = document.getElementById("QuantCaptura").getContext("2d");
//        var QuantCaptChart = new Chart(id_quant_capt).Bar(dataquantcaptura, options);
    };
</script>

<!--<script src="js/charts-box/Chart.js"></script>-->
<!--<script type="text/javascript">
    var optionsBox = {
		
                whiskerWidth : 0.75,
                scaleOverride: true,
                scaleStartValue: 0,
                scaleSteps: 6,
                scaleStepWidth: 1,
                bezierCurve: true,
                datasetFill: false,
                connectingLine : true,
                animation : true
		};
        var cpueArrasto = {
        labels: <?= $this->labels ?>,
        datasets: [
            {
                label: "Quantidade",
                fillColor: "rgba(95,48,43,.8)",
                strokeColor: "rgba(95,48,43,1)",
                pointColor: "rgba(95,48,43,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(95,48,43,1)",
                data: [<?= $this->cpue ?>]
            }
        ]
    };
    window.onload = function(){
        var myLine = new ChartCalculator(
        document.getElementById("cpueArrasto").getContext("2d")).Box(cpueArrasto, optionsBox);
        

    }
</script>-->
<br/>
<div class="box-chart">
    <legend>Gráfico 1: Número de Pescarias por Mês</legend>
  <canvas id="EntrevistasByMes" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 2: Total de Capturas em kg por Mês</legend>
  <canvas id="CapturaByMes" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 3: Embarcacoes Monitoradas</legend>
  <canvas id="BarcosMonitorados" style="width:100%;"></canvas>
</div>
<br/>