<h2>Porto -> Aritaguá</h2>

<script src="js/Chart.min.js"></script>

<script type="text/javascript">

    var options = {
        responsive:true,
        scaleOverride: false

    };
    var optionsCaptura = {
        responsive:true,
        scaleOverride: true,
	scaleStartValue: 0,
	scaleSteps: 15,
	scaleStepWidth: 1000
    };
    var responsive_false = {
        responsive:false
    };
 
 
    var artesMonitoradas = {
       labels: <?= $this->arrayPorArteLabels ?>,
       datasets: [
           {
               label: "Quantidade",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->arrayPorArteQtds ?>
           }
       ]
   };
 
   var entrevistasByMes1 = {
       labels: <?= $this->quantLabelsJerere ?>,
       datasets: [
           {
               label: "Quantidade de Entrevistas Por Mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantEntrevistasJerere ?>
           }
       ]
   };
   var capturaByMes1 = {
       labels: <?= $this->countCaptLabelsJerere ?>,
       datasets: [
           {
               label: "Captura total por mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->countCaptPesoJerere ?>
           }
       ]
   };
   var Embarcacoes1 = {
       labels: <?= $this->labelBarcosJerere ?>,
       datasets: [
           {
               label: "Barcos Mais Monitorados",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantBarcosJerere ?>
           }
       ]
   };
   

//   
   var especiesCapturadas1 = {
       labels: <?= $this->labelCapturaJerere ?>,
       datasets: [
           {
               label: "Quantidade",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->pesoCapturaJerere ?>
           }
       ]
   };
    
   var entrevistasByMes2 = {
       labels: <?= $this->quantLabelsRatoeira ?>,
       datasets: [
           {
               label: "Quantidade de Entrevistas Por Mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantEntrevistasRatoeira ?>
           }
       ]
   };
      var capturaByMes2 = {
       labels: <?= $this->countCaptLabelsRatoeira ?>,
       datasets: [
           {
               label: "Captura total por mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->countCaptQuantidadeRatoeira ?>
           }
       ]
   };
   var Embarcacoes2 = {
       labels: <?= $this->labelBarcosRatoeira ?>,
       datasets: [
           {
               label: "Barcos Mais Monitorados",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantBarcosRatoeira ?>
           }
       ]
   };
   
//   
   var especiesCapturadas2 = {
       labels: <?= $this->labelCapturaRatoeira ?>,
       datasets: [
           {
               label: "Quantidade",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->pesoCapturaRatoeira ?>
           }
       ]
   };

    
    window.onload = function(){
        var id_barcos = document.getElementById("ArtesMonitoradas").getContext("2d");
        var BarChart = new Chart(id_barcos).Bar(artesMonitoradas, options);
        
        //PESCA PRINCIPAL
        //2
        var ctx = document.getElementById("EntrevistasByMes").getContext("2d");
        var EntrevistasChart = new Chart(ctx).Bar(entrevistasByMes1, options);
        
        //3
        var ctx = document.getElementById("CapturaByMes").getContext("2d");
        var CapturaChart = new Chart(ctx).Bar(capturaByMes1, options);

        //4
        var ctx = document.getElementById("BarcosMonitorados").getContext("2d");
        var EmbarcacoesCharts = new Chart(ctx).Bar(Embarcacoes1, options);

        //5
        var id_quant_barcos = document.getElementById("EspeciesCapturadas").getContext("2d");
        var EspeciesCapturadas = new Chart(id_quant_barcos).Bar(especiesCapturadas1, options);
        //PESCA PRINCIPAL
        
        
        //PESCA SECUNDÁRIA
        //6
        var ctx = document.getElementById("EntrevistasByMes2").getContext("2d");
        var EntrevistasChart = new Chart(ctx).Bar(entrevistasByMes2, options);
        
        //7
        var ctx = document.getElementById("CapturaByMes2").getContext("2d");
        var CapturaChart = new Chart(ctx).Bar(capturaByMes2, options);
        
        //8
        var ctx = document.getElementById("BarcosMonitorados2").getContext("2d");
        var EmbarcacoesCharts = new Chart(ctx).Bar(Embarcacoes2, options);
        
        //9
        var id_quant_barcos = document.getElementById("EspeciesCapturadas2").getContext("2d");
        var EspeciesCapturadas = new Chart(id_quant_barcos).Bar(especiesCapturadas2, options);
        //PESCA SECUNDARIA
    };
</script>



<h4>Ilhéus – Rio Almada – Aritaguá</h4>
<p>Os pescadores e marisqueiras de Aritaguá atuam ao longo do Rio Almada, que margeia a comunidade, e desembarcam principalmente no fundo das próprias casas ou no atracadouro onde funcionava a antiga balsa. Os pescados são destinados à subsistência e/ou comercializados na comunidade e feiras do centro de Ilhéus.</p>

<img class="img-porto" src="<?= 'img/portos/'.$this->porto.'.jpg'?>"/>

Figura: Aritaguá.	
<p>A maioria dos pescadores locais pesca utilizando mais de uma arte de pesca. As artes utilizadas com maior frequência em Aritaguá são o jereré e a ratoeira .</p>


<br/>
<div class="box-chart">
    <legend>Gráfico 1: Artes de Pesca Mais Monitoradas (%)</legend>
  <canvas id="ArtesMonitoradas" style="width:100%;"></canvas>
</div>
<br/>

<h4> Monitoramentos com Pesca de <?= $this->arteMaisPescada?> </h4>
<br/>
<div class="box-chart">
    <legend>Gráfico 2: Número de Pescarias por Mês na Pesca de <?= $this->arteMaisPescada?></legend>
  <canvas id="EntrevistasByMes" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 3: Total de Capturas em kg por Mês na Pesca de <?= $this->arteMaisPescada?></legend>
  <canvas id="CapturaByMes" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 4: Espécies Mais Capturadas na Pesca de <?= $this->arteMaisPescada?></legend>
  <canvas id="EspeciesCapturadas" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 5: Embarcacoes Monitoradas na Pesca de <?= $this->arteMaisPescada?></legend>
  <canvas id="BarcosMonitorados" style="width:100%;"></canvas>
</div>
<br/>


<h4> Monitoramentos com Pesca de <?= $this->segArteMaisPescada?> </h4>
<br/>
<div class="box-chart">
    <legend>Gráfico 6: Número de Pescarias por Mês na Pesca de <?= $this->segArteMaisPescada?></legend>
  <canvas id="EntrevistasByMes2" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 7: Total de Capturas em kg por Mês na Pesca de <?= $this->segArteMaisPescada?></legend>
  <canvas id="CapturaByMes2" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 8: Espécies Mais Capturadas na Pesca de <?= $this->segArteMaisPescada?></legend>
  <canvas id="EspeciesCapturadas2" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 9: Embarcacoes Monitoradas na Pesca de <?= $this->segArteMaisPescada?></legend>
  <canvas id="BarcosMonitorados2" style="width:100%;"></canvas>
</div>
<br/>

