<h3>Relatórios -> Portos:</h3>

    <ul>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Pontal</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Terminal Pesqueiro</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Prainha</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Amendoeira</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Porto da Barra</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">São Miguel</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Ponta da Tulha</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Mamoã</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Ponta do Ramo</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Urucutuca</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Sambaituba</a></li>      
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Juerana Rio</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Aritaguá</a></li>    
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Sobradinho</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Pé de Serra</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Vila Badú</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Porto da Concha</a></li>
        <li><a class="relatorio" href="<?= $this->url(array("controller" => "porto", "action" => ""), null, true) ?>"target="_blank">Porto do Forte</a></li>
    </ul>    