<h3>Relatórios -> Portos:</h3>

<form action="<?= $this->url(array("controller" => "porto", "action" => "relatorioindex"), null, true) ?>" method="post">
    <div class="esquerda">

        <fieldset>
            <legend>Entrevistas:</legend>
            <div class="form-esq">
                <label>Portos:</label><select name="porto" >
                    <option value="1">Pontal</option>
                    <option value="2">Terminal Pesqueiro</option>
                    <option value="3">Prainha</option>
                    <option value="4">Amendoeira</option>
                    <option value="5">Porto da Barra</option>
                    <option value="6">São Miguel</option>
                    <option value="7">Ponta da Tulha</option>
                    <option value="8">Mamoã</option>
                    <option value="9">Ponta do Ramo</option>
                    <option value="10">Urucutuca</option>
                    <option value="11">Sambaituba</option>      
                    <option value="12">Juerana</option>
                    <option value="13">Aritaguá</option>    
                    <option value="14">Sobradinho</option>
                    <option value="15">Pé de Serra</option>
                    <option value="16">Vila Badú</option>
                    <option value="17">Porto da Concha</option>
                    <option value="18">Porto do Forte</option>
                </select>
            </div>
            <div class="form-esq">
            <label>Ano:</label>
            <input type="number" name="ano" min="2013" max="<?= date("Y") ?>"/>
            </div>
            
            <br/>
            <input type="submit" value="Enviar"/>
        </fieldset>
    </div>
</form>