<h2>Porto -> Terminal Pesqueiro</h2>

<script src="js/Chart.min.js"></script>
<a href="<?= $this->url(array("controller" => "porto", "action" => "relatorioindex"), null, true) ?>" id="botao-ancora">Voltar</a><br/>
<a id="pdf" href="javascript:print();" title="Gerar PDF"><img src="img/pdf-icon.png" class="icon-relatorios"></a><br/>
<script type="text/javascript">

    var options = {
        responsive:true,
        scaleOverride: false

    };
    var optionsCaptura = {
        responsive:true,
        scaleOverride: true,
	scaleStartValue: 0,
	scaleSteps: 15,
	scaleStepWidth: 1000
    };
    var responsive_false = {
        responsive:false
    };
 
 
    var artesMonitoradas = {
       labels: <?= $this->arrayPorArteLabels ?>,
       datasets: [
           {
               label: "Quantidade",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->arrayPorArteQtds ?>
           }
       ]
   };
 
   var entrevistasByMes1 = {
       labels: <?= $this->quantLabelsArrasto ?>,
       datasets: [
           {
               label: "Quantidade de Entrevistas Por Mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantEntrevistasArrasto ?>
           }
       ]
   };
   var capturaByMes1 = {
       labels: <?= $this->countCaptLabelsArrasto ?>,
       datasets: [
           {
               label: "Captura total por mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->countCaptPesoArrasto ?>
           }
       ]
   };
   var Embarcacoes1 = {
       labels: <?= $this->labelBarcosArrasto ?>,
       datasets: [
           {
               label: "Barcos Mais Monitorados",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantBarcosArrasto ?>
           }
       ]
   };
   

//   
   var especiesCapturadas1 = {
       labels: <?= $this->labelCapturaArrasto ?>,
       datasets: [
           {
               label: "Quantidade",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->pesoCapturaArrasto ?>
           }
       ]
   };
    
   var entrevistasByMes2 = {
       labels: <?= $this->quantLabelsGrosseira ?>,
       datasets: [
           {
               label: "Quantidade de Entrevistas Por Mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantEntrevistasGrosseira ?>
           }
       ]
   };
      var capturaByMes2 = {
       labels: <?= $this->countCaptLabelsGrosseira ?>,
       datasets: [
           {
               label: "Captura total por mês",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->countCaptPesoGrosseira ?>
           }
       ]
   };
   var Embarcacoes2 = {
       labels: <?= $this->labelBarcosGrosseira ?>,
       datasets: [
           {
               label: "Barcos Mais Monitorados",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantBarcosGrosseira ?>
           }
       ]
   };
   
//   
   var especiesCapturadas2 = {
       labels: <?= $this->labelCapturaGrosseira ?>,
       datasets: [
           {
               label: "Quantidade",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->pesoCapturaGrosseira ?>
           }
       ]
   };

    
    window.onload = function(){
        var id_barcos = document.getElementById("ArtesMonitoradas").getContext("2d");
        var BarChart = new Chart(id_barcos).Bar(artesMonitoradas, options);
        
        //PESCA PRINCIPAL
        //2
        var ctx = document.getElementById("EntrevistasByMes").getContext("2d");
        var EntrevistasChart = new Chart(ctx).Bar(entrevistasByMes1, options);
        
        //3
        var ctx = document.getElementById("CapturaByMes").getContext("2d");
        var CapturaChart = new Chart(ctx).Bar(capturaByMes1, options);

        //4
        var ctx = document.getElementById("BarcosMonitorados").getContext("2d");
        var EmbarcacoesCharts = new Chart(ctx).Bar(Embarcacoes1, options);

        //5
        var id_quant_barcos = document.getElementById("EspeciesCapturadas").getContext("2d");
        var EspeciesCapturadas = new Chart(id_quant_barcos).Bar(especiesCapturadas1, options);
        //PESCA PRINCIPAL
        
        
        //PESCA SECUNDÁRIA
        //6
        var ctx = document.getElementById("EntrevistasByMes2").getContext("2d");
        var EntrevistasChart = new Chart(ctx).Bar(entrevistasByMes2, options);
        
        //7
        var ctx = document.getElementById("CapturaByMes2").getContext("2d");
        var CapturaChart = new Chart(ctx).Bar(capturaByMes2, options);
        
        //8
        var ctx = document.getElementById("BarcosMonitorados2").getContext("2d");
        var EmbarcacoesCharts = new Chart(ctx).Bar(Embarcacoes2, options);
        
        //9
        var id_quant_barcos = document.getElementById("EspeciesCapturadas2").getContext("2d");
        var EspeciesCapturadas = new Chart(id_quant_barcos).Bar(especiesCapturadas2, options);
        //PESCA SECUNDARIA
    };
</script>



<h4>Ilhéus - Sede Municipal – Terminal Pesqueiro</h4>
<p>Localizado no centro de Ilhéus o Terminal Pesqueiro de Ilhéus é administrado pela Bahia Pesca, apresenta um píer de atracação (na Baia do Pontal) e uma área para venda dos produtos.</p>

<p>Além disso, disponibiliza a venda de água, gelo e combustível.</p>

<img class="img-porto" src="<?= 'img/portos/'.$this->porto.'.jpg'?>"/>

Figura: Terminal Pesqueiro.	
<p>O Terminal Pesqueiro não é utilizado apenas por pescadores de Ilhéus, eventualmente embarcações de outros municípios e estados utilizam a área para desembarcar e reabastecer. As embarcações que utilizam o Terminal Pesqueiro atuam principalmente em três artes de pesca: linha de mão, espinhel e arrasto. Raramente alguns pescadores realizam pescarias de mergulho e siripoía no próprio local. A principal arte de pesca utilizada é o arrasto de fundo, totalizando mais de 50% dos desembarques monitorados.</p>

<br/>
<div class="box-chart">
    <legend>Gráfico 1: Artes de Pesca Mais Monitoradas (%)</legend>
  <canvas id="ArtesMonitoradas" style="width:100%;"></canvas>
</div>
<br/>

<h4> Monitoramentos com Pesca de <?= $this->arteMaisPescada?> </h4>
<br/>
<div class="box-chart">
    <legend>Gráfico 2: Número de Pescarias por Mês na Pesca de <?= $this->arteMaisPescada?></legend>
  <canvas id="EntrevistasByMes" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 3: Total de Capturas em kg por Mês na Pesca de <?= $this->arteMaisPescada?></legend>
  <canvas id="CapturaByMes" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 4: Espécies Mais Capturadas na Pesca de <?= $this->arteMaisPescada?></legend>
  <canvas id="EspeciesCapturadas" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 5: Embarcacoes Monitoradas na Pesca de <?= $this->arteMaisPescada?></legend>
  <canvas id="BarcosMonitorados" style="width:100%;"></canvas>
</div>
<br/>


<h4> Monitoramentos com Pesca de <?= $this->segArteMaisPescada?> </h4>
<br/>
<div class="box-chart">
    <legend>Gráfico 6: Número de Pescarias por Mês na Pesca de <?= $this->segArteMaisPescada?></legend>
  <canvas id="EntrevistasByMes2" style="width:100%;"></canvas>
</div>
<br/>
<br/>
<div class="box-chart">
    <legend>Gráfico 7: Total de Capturas em kg por Mês na Pesca de <?= $this->segArteMaisPescada?></legend>
  <canvas id="CapturaByMes2" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 8: Espécies Mais Capturadas na Pesca de <?= $this->segArteMaisPescada?></legend>
  <canvas id="EspeciesCapturadas2" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 9: Embarcacoes Monitoradas na Pesca de <?= $this->segArteMaisPescada?></legend>
  <canvas id="BarcosMonitorados2" style="width:100%;"></canvas>
</div>
<br/>

<a href="<?= $this->url(array("controller" => "porto", "action" => "cpue", "ano" => $this->ano, "arte" => $this->arteMaisPescada, "porto" => $this->porto ), null, true) ?>" id="botao-ancora">Gráfico de CPUE em <?=$this->arteMaisPescada?></a><br/>
<a href="<?= $this->url(array("controller" => "porto", "action" => "cpue", "ano" => $this->ano, "arte" => $this->segArteMaisPescada, "porto" => $this->porto ), null, true) ?>" id="botao-ancora">Gráfico de CPUE em <?=$this->segArteMaisPescada?></a><br/>