<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="5%">Id Entrevista</th>
            <th width="50%">Pesqueiro</th>
            <th width="30%">Tempo até o Pesqueiro</th>
            <th width="30%">Distância até o Pesqueiro</th>
            </tr>
            <?php
            foreach ($this->vManzua as $key => $vManzua):
                ?>
                <tr id="itemManzuaRows">
                <td name="inputIdEntrevista"> <?= $vManzua['man_id'] ?> </td>
                <td name="inputPesqueiro" > <?= $vManzua['paf_pesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vManzua['t_tempoapesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vManzua['t_distapesqueiro'] ?> </td>
                <td><input type="button" class="button-del" width="5%" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['man_id'] ?>, '<?= $this->url(array("controller" => "manzua", "action" => "deletepesqueiro"), null, true) ?>', <?= $vManzua['man_paf_id'] ?>, 'pesqueiro')"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>