<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="15%">Id Entrevista</th>
            <th width="45%">Pesqueiro</th>
            <th width="20%">Tempo até o Pesqueiro</th>
            <th width="20%">Distância até o Pesqueiro</th>
            </tr>
            <?php
            foreach ($this->vManzua as $key => $vManzua):
                ?>
                <tr id="itemManzuaRows">
                <td name="inputIdEntrevista"> <?= $vManzua['man_id'] ?> </td>
                <td name="inputPesqueiro" > <?= $vManzua['paf_pesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vManzua['t_tempoapesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vManzua['t_distapesqueiro'] ?> </td>
                <td class="td-botao">
                    <a name="Editar" class="button-del" onclick="ajax_update_pesqueiro('<?= $vManzua['man_paf_id'] ?>','<?= $vManzua['paf_id'] ?>','', '<?= $vManzua['t_tempoapesqueiro'] ?>', '<?= $vManzua['t_distapesqueiro'] ?>', document.getElementById('formEntrevistas'))">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a> 
                </td>
                <td class="td-botao">
                    <a name="Excluir" class="button-del" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['man_id'] ?>, '<?= $this->url(array("controller" => "manzua", "action" => "deletepesqueiro"), null, true) ?>', <?= $vManzua['man_paf_id'] ?>, 'pesqueiro')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>