<h2>Desembarque->Iscas</h2>

<fieldset id="dadosDesembarque"></fieldset>
<form>
<a id="ancora_dependentes"></a>
    <fieldset class="noEditable"><legend>Iscas:</legend>
        <fieldset class="noEditable"><legend>Adicionar Isca:</legend>
            <div id="base">
                <input type="button" name="Add" class="button-confirm" onclick="jsInsertIsca(this.form, '<?= $this->url(array("controller" => "isca", "action" => "insert"), null, true) ?>')">
                <input type="button" name="Reload" class="button-clear" onclick="jsReloadIsca(this.form)">

                <input type="text" name="inputIsc_tipo" placehol    der="Tipo de isca" size="40"  />
                <input readonly="" type="text" name="inputIsc_id" />
            </div>
        </fieldset>
        <br>

<table>
    <tr>
        <th>ID</th>
        <th>Nome</th>
    </tr>
    
    <?php foreach ($this->dadosIscas as $key => $isca): ?>
    <tr>
        <td><?= $isca['isc_id'] ?></td>
        <td><?= $isca['isc_tipo'] ?></td>
        <td class="td-botao">
            <input type="button" name="Excluir" class="button-del" onclick="jsDeleteIsca(<?=$isca['isc_id']?>,'<?= $this->url(array("controller" => "isca", "action" => "delete"), null, true) ?>')">

        </td>
    </tr>
    <?php endforeach; ?>
</table>
<br/><br/>
<a href="<?=$this->url(array("controller"=>"isca","action"=>"relatorio"),null,true)?>" id="botao-ancora" target="_blank">Gerar Relatório</a>

</fieldset>
</form>