<script>
            function ajax_post(){
            // Create our XMLHttpRequest object
            var hr = new XMLHttpRequest();
            // Create some variables we need to send to our PHP file
            var url = "<?= $this->url(array("controller" => "isca", "action" => "insert"), null, true) ?>";
            var fn = document.getElementById("inputIsc_tipo").value;
            //var ln = document.getElementById("last_name").value;
            var vars = "isc_tipo="+fn;//"&lastname="+ln;
            hr.open("POST", url, true);
            // Set content type header information for sending url encoded variables in the request
            hr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            // Access the onreadystatechange event for the XMLHttpRequest object
            hr.onreadystatechange = function() {
                    if(hr.readyState === 4 && hr.status === 200) {
                    var return_data = hr.responseText;
                        document.getElementById("status").innerHTML = return_data;
            }
                }
                // Send the data to PHP now... and wait for response to update the status div
                hr.send(vars); // Actually execute the request
                document.getElementById("status").innerHTML = "processing...";
            }
        </script>

<h2>Desembarque->Iscas</h2>

<fieldset id="dadosDesembarque"></fieldset>
<form>
<a id="ancora_dependentes"></a>
    <fieldset class="noEditable"><legend>Iscas:</legend>
        <fieldset class="noEditable"><legend>Adicionar Isca:</legend>
            <div id="base">
                <input type="button" name="Add" id="add" class="busca" value="Adicionar" onclick="ajax_post();">
                <input type="button" name="Reload" class="busca" value="Limpar campos" onclick="jsReloadIsca(this.form)">

                <input type="text" name="inputIsc_tipo" id="inputIsc_tipo" placeholder="Tipo de isca" size="40"  />
                <input readonly="" type="text" name="inputIsc_id" />
            </div>
        </fieldset>
        <br>
        
        <?php include('table.phtml'); ?>
    </fieldset>
</form>