<h2>Desembarque->Ficha Diária</h2>

<fieldset id="Desembarque"></fieldset>
 <form name="indexFichaDiaria" method="post">

     <a href="<?= $this->url(array("controller" => "ficha-diaria", "action" => "novo"), null, true) ?>" id="botao-ancora">Novo</a>
        
     <input type="button" class="tam_medio" value="Limpar" onClick="jsClearBusca('<?= $this->url(array("controller" => "ficha-diaria", "action" => "index"), null, true) ?>')"/>
     <input type="button" class="tam_medio" value="Buscar" onClick="jsBuscaFichaDiaria(this.form, '<?= $this->url(array("controller" => "ficha-diaria", "action" => "index"), null, true) ?>')"/>
     <select name="tipoBusca">
        <option value="1">Por ID</option>
        <option value="2">Por Data</option>
        <option value="4">Por Porto</option>
        <option value="5">Por Estagiário</option>
        <option value="6">Por Monitor</option>
     </select>
            <input id="busca"  name="buscaFicha" placeholder="Buscar Ficha Diária"/><br/>
<table id="tabelaComEstilo">
    <tr>
        <th>ID</th>
        <th>Data</th>
        <th>Turno</th>
        <th>Porto</th>
        <th>Estagiário</th>
        <th>Monitor</th>

    </tr>

    <?php foreach ($this->dados as $key => $fichadiaria): ?>
    <tr>
        <td width="10%"><?= $fichadiaria['fd_id'] ?></td>
        <td width="10%"><?= date("d-m-Y", strtotime($fichadiaria['fd_data']))  ?></td>
        <td width="5%"><?= $fichadiaria['fd_turno'] ?></td>
        <td width="10%"><?= $fichadiaria['pto_nome'] ?></td>
        <td width="30%"><?= $fichadiaria['t_estagiario'] ?></td>
        <td width="20%"><?= $fichadiaria['t_monitor'] ?></td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"ficha-diaria","action"=>"editar", "id" => $fichadiaria['fd_id']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                </ul>
            </a>
        </td>
        
        <td  class="td-botao">
            <a type="button" value="Excluir" onclick="beforeDelete('<?= $this->url(array("controller" => "ficha-diaria", "action" => "excluir", "id" => $fichadiaria['fd_id']), null, true) ?>')">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                </ul>
             </a>
            
        </td>
        <td  class="td-botao">
            <a href="<?=$this->url(array("controller"=>"ficha-diaria","action"=>"imprimirfichaid", "id" => $fichadiaria['fd_id']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Imprimir"><span class="ui-icon ui-icon-print"></span></li>
                </ul>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
            <br/>
            <br/>
     <a href="<?= $this->url(array("controller" => "ficha-diaria", "action" => "imprimirfichatodas"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
 </form>
