<div class="form-esq" id="pescadoresAction">    
    <label>Pescador Entrevistado:</label>
    <select name="pescadorEntrevistado" required/>
    <option value="" selected></option>
    <?php
    foreach ($this->pescadores as $key => $pescador):
        ?>
        <option value="<?= $pescador['tp_id'] ?>"><?= $pescador['tp_nome'] . ' ( ' . $pescador['tp_apelido'] . ' )' ?></option>
        <?php
    endforeach;
    ?>
</select>
<br />
</div>