<fieldset id="Entrevista"></fieldset>
    <form name="grosseira" method="post">

        <h2>Entrevistas Cadastradas->Pesca de Groseira (lista limitada em 20)</h2>

        <input type="button" value="Limpar" onClick="jsClearBusca('<?= $this->url(array("controller" => "grosseira", "action" => "visualizar"), null, true) ?>')"/>
        <input type="button" value="Buscar" onClick="jsBuscaEntrevistas(this.form, '<?= $this->url(array("controller" => "grosseira", "action" => "visualizar"), null, true) ?>')"/>
            <select name="tipoBusca">
                <option value="1">Por ID</option>
                <option value="2">Por Pescador</option>
                <option value="3">Por Barco</option>
                <option value="4">Por Apelido</option>
                <option value="6">Listar Todas</option>
            </select>
        <input id="busca" name="buscaEntrevistas" placeholder="Buscar Entrevista"/><br/>
        <table>
            <tr>
                <th>Ficha Diária</th>
                <th>Monitoramento</th>
                <th>Entrevista</th>
                <th>Pescador</th>
                <th>Apelido</th>
                <th>Barco</th>
            </tr>

            <?php foreach ($this->dados as $key => $entrevista): ?>
                <tr>
                    <td><?= $entrevista['fd_id']?></td>
                    <td><?= $entrevista['mnt_id'] ?></td>
                    <td><?= $entrevista['grs_id'] ?></td>
                    <td><?= $entrevista['tp_nome'] ?></td>
                     <td><?= $entrevista['tp_apelido'] ?></td>
                    <td><?= $entrevista['bar_nome'] ?></td>

                    <td class="td-botao">
                        <a href="<?= $this->url(array("controller" => "grosseira", "action" => "editar", "id" => $entrevista['grs_id']), null, true) ?>">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                            </ul>
                        </a>
                    </td>

                    <td class="td-botao">
                        <a name="Excluir" class="button-del" onclick="beforeDelete('<?= $this->url(array("controller" => "grosseira", "action" => "excluir", "id" => $entrevista['grs_id']), null, true) ?>')">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                            </ul>
                        </a> 
                    </td>

                    </a>

                </tr>
            <?php endforeach; ?>
        </table>
        <br/><br/>
        <a href="<?= $this->url(array("controller" => "pescador", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
    </form>
</html>
