<div id="titulos">
    <h2>Desembarque->Pesca de Emalhe</h2>
    <h3>Entrevista</h3>
</div>

<div class="esquerda-entrevista">
    <form action="<?= $this->url(array("controller" => "emalhe", "action" => "criar"), null, true) ?>" name="entrevista" onSubmit="return verificaDataEmalhe()">
        <fieldset id="Entrevista">
            <div class="esquerda">
                <div class="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" disabled="true" value="<?= $this->fichaDiaria['fd_id'] ?>" /><br />
                </div>
                <div class="form-esq">
                    <label>ID Monitoramento:</label>
                    <input type="text" name="id_monitoramento" placeholder="ID"  value="<?= $this->monitoramento['mnt_id'] ?>" /><br />
                </div>
                <div class="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" placeholder = "ID" name="id_entrevista" disabled="true"/><br />
                </div>
            </div>
            <br/>
            <div class="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div class="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox"  name="embarcada" /><br />
                </div>
                <div class="form-esq">
                    <label>Motor?</label>
                    <input type="checkbox"  name="motor"/><br />
                </div>
                <div class="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco"  required/>
                        <option value="" selected></option>
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>"><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div class="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" required/>
                        <option value="" selected></option>
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>"><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>

            </div>
            <div class="direita-entrevista">
                <div class="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="pescadorEntrevistado" required/>
                        <option value="" selected></option>
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>"><?= $pescador['tp_nome'] .' ( '. $pescador['tp_apelido']. ' )' ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div class="form-esq">
                    <label>Quant. de Pescadores:</label>
                    <input type="number" name="numPescadores" min="1" placeholder="Quantidade de Pescadores" required/><br />
                </div>
            </div>
            <div class="esquerda">
                <legend><h4>Lançamento e Recolhimento:</h4></legend>
                <div class="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataLancamento" min="2013-11-01" required/>
                </div>
                <div class="form-esq">
                    <label>Hora:</label>
                    <input type="time" name="horaLancamento" required/>
                </div>
            </div>
            <div class="direita-entrevista">
                <div class="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataRecolhimento" min="2013-11-01" required/>
                </div>
                <div class="form-esq">
                    <label>Hora:</label>
                    <input type="time" name="horaRecolhimento" required/>
                </div>
            </div>
            <div class="esquerda">
                <div class="form-esq">
                    <legend><h4>Gastos:</h4></legend>
                    <label>Diesel(L):</label>
                    <input type="text"  name="diesel" placeholder="Diesel"/>
                </div>
                <div class="form-dir">    
                    <label>Óleo(L):</label>
                    <input type="text"  name="oleo" placeholder="Óleo"/><br />
                </div>
            </div>
            <div class="direita-entrevista">
                <div class="form-dir">    
                    <label>Alimento($):</label>
                    <input type="text"  name="alimento" placeholder="Alimento"/><br />
                </div>
                <div class="form-dir">    
                    <label>Gelo($):</label>
                    <input type="text"  name="gelo" placeholder="Gelo"/><br />
                </div>
            </div>
            <div class="esquerda">
                <div class="form-esq">
                    <legend><h4>Esforço:</h4></legend>
                    <label>Tamanho(m):</label>
                    <input type="text"  name="tamanho" placeholder="Tamanho"/>
                </div>
                <div class="form-dir">    
                    <label>Altura(m):</label>
                    <input type="text"  name="altura" placeholder="Altura"/><br />
                </div>
            </div>
            <div class="direita-entrevista">
                <div class="form-dir">    
                    <label>Número de Panos:</label>
                    <input type="text"  name="numPanos" placeholder="Panos"/><br />
                </div>
                <div class="form-dir">    
                    <label>Malha:</label>
                    <input type="text"  name="malha" placeholder="Malha"/><br />
                </div>
            </div><br/>
            <br/>
            <div class="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div class="form-esq">    
                    <label>Destino do Pescado:</label>
                    <select name="destinoPescado" required/>
                        <option value="" selected></option>
                    <?php
                    foreach ($this->destinos as $key => $destino):
                        ?>
                        <option value="<?= $destino['dp_id'] ?>"><?= $destino['dp_destino'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                </div>
                <div class="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" name="subamostra" /><br />
                </div>
                <div class="form-esq">
                    <label for="tipo">Observacao:</label>
                    <input type="text" name="observacao" placeholder="Observacao" /><br />
                </div>

                <div class="Submit">
                    <input type="submit" value="Salvar Entrevista"/>
                </div>
            </div>

        </fieldset>
    </form>        
</div>      
