<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="15%">Id Entrevista</th>
            <th width="85%">Pesqueiro</th>
            </tr>
            <?php
            foreach ($this->vEmalhe as $key => $vEmalhe):
                ?>
                <tr id="itemEmalheRows">
                <td name="inputIdEntrevista"> <?= $vEmalhe['em_id'] ?> </td>
                <td name="inputPesqueiro"> <?= $vEmalhe['paf_pesqueiro'] ?> </td>
                <td class="td-botao">
                    <a name="Editar" class="button-del" onclick="ajax_update_pesqueiro('<?= $vEmalhe['em_paf_id'] ?>','<?= $vEmalhe['paf_id'] ?>', '', '', document.getElementById('formEntrevistas'))">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a> 
                </td>
                <td class="td-botao">
                    <a name="Excluir" class="button-del" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['em_id'] ?>, '<?= $this->url(array("controller" => "emalhe", "action" => "deletepesqueiro"), null, true) ?>', <?= $vEmalhe['em_paf_id'] ?>, 'pesqueiro')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>