<h2>Pescador Especialista -> Órgão de RGP</h2>
<form method="post">
<fieldset id="Especialista"></fieldset>

    <a id="ancora_orgao-rgp"></a>
    <fieldset class="noEditable"><legend>Órgão de RGP:</legend>
        <fieldset class="noEditable"><legend>Adicionar Órgão de RGP:</legend>
            <div id="base">
                <input type="button" name="Add" class="button-confirm" onclick="jsInsertDynamic(this.form, '<?= $this->url(array("controller" => "orgao-rgp", "action" => "insert"), null, true) ?>', '<?= $this->url(array("controller" => "orgao-rgp", "action" => "update"), null, true) ?>')">
                <input type="button" name="Reload" class="button-clear" onclick="jsReloadDynamic(this.form)">

                <input type="text" name="input_valor" placeholder="Companhia de Pesca" size="40"  />
                <input readonly="" type="text" name="input_id" />
            </div>
        </fieldset>
        <br>

        <table id="tblPerfil">
            <tr>
                <th width="15%">ID </th>
                <th width="65%">Órgão de RGP</th>
            </tr>
            <?php foreach ($this->assignOrgaoRgp as $key => $dadosOrgaoRgp): ?>
                <tr id="rowNumPeril<?= $key ?>">
                    <td><?= $dadosOrgaoRgp['trgp_id'] ?></td>
                    <td><?= $dadosOrgaoRgp['trgp_emissor'] ?></td>
                    <td><input type="button" class="button-edit" width="5%" onclick="jsUpdateDynamic('<?= $dadosOrgaoRgp['trgp_id'] ?>', '<?= $dadosOrgaoRgp['trgp_emissor'] ?>', this.form)"></td>
                    <td><input type="button" class="button-del" width="5%" onclick="jsDeleteDynamic(<?= $dadosOrgaoRgp['trgp_id'] ?>, '<?= $this->url(array("controller" => "orgao-rgp", "action" => "delete"), null, true) ?>')"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
    <fieldset class="noBorder">
        <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
        <a href="<?= $this->url(array("controller" => "orgao-rgp", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório - Lista</a>
    </fieldset>
</form>