<div id="biocamarao">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Dados Cadastrados:</legend>
        <table id="especiesCapturadas">
            <tr>

            <th width="20%">Id Amostra</th>
            <th width='20%'>Espécie</th>
            <th width="10%">Sexo</th>
            <th width="20%">Maturidade</th>
            <th width="20%">Comp.Carapaça</th>
            <th width="20%">Peso</th>
            </tr>
            <?php
            foreach ($this->vBioCamarao as $key => $unidadeCamarao):
                ?>
                <tr id="itemEmbarcacoesRows">

                <td name="inputAmostra"> <?= $unidadeCamarao['tcmlbc_id'] ?> </td>
                <td name="inputEspecie"> <?= $unidadeCamarao['esp_nome_comum'] ?> </td>
                <td name="inputSexo"> <?= $unidadeCamarao['tbc_sexo'] ?> </td>
                <td name="inputMaturidade"> <?= $unidadeCamarao['tmat_tipo'] ?> </td>
                <td name="inputComp.Cabeca"> <?= $unidadeCamarao['tbc_comprimento_cabeca'] ?> </td>
                <td name="inputPeso"> <?= $unidadeCamarao['tbc_peso'] ?> </td>
                <td class="td-botao">
                    <a name="Editar" class="button-del" onclick="ajax_update_bio_camarao(<?= $unidadeCamarao['tcmlbc_id'] ?>, '<?= $unidadeCamarao['esp_id'] ?>', '<?= $unidadeCamarao['tbc_comprimento_cabeca'] ?>', '<?= $unidadeCamarao['tbc_sexo'] ?>','<?= $unidadeCamarao['tbc_peso'] ?>','<?= $unidadeCamarao['tmat_id'] ?>', document.getElementById('formEntrevistas'))">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a>
                </td>
                <td class="td-botao">
                    <a name="Excluir" class="button-del" onclick="ajax_delete_entrevista_has('<?= $this->entrevista['cml_id'] ?>', '<?= $this->url(array("controller" => "coleta-manual", "action" => "deletebiocamarao"), null, true) ?>', '<?= $unidadeCamarao['tcmlbc_id'] ?>', 'biocamarao')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>