<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="15%">Id Entrevista</th>
            <th width="40%">Pesqueiro</th>
            <th width="20%">Tempo até o Pesqueiro</th>
            <th width="25%">Distância até o Pesqueiro</th>
            </tr>
            <?php
            foreach ($this->vColetaManual as $key => $vColetaManual):
                ?>
                <tr id="itemArrastoRows">
                <td name="inputIdEntrevista"> <?= $vColetaManual['cml_id'] ?> </td>
                <td name="inputPesqueiro" > <?= $vColetaManual['paf_pesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vColetaManual['t_tempoapesqueiro'] ?> </td>
                <td name="inputDistanciaaPesqueiro"> <?= $vColetaManual['t_distapesqueiro'] ?> </td>
                <td class="td-botao">
                    <a name="Editar" class="button-del" onclick="ajax_update_pesqueiro('<?= $vColetaManual['cml_paf_id'] ?>','<?= $vColetaManual['paf_id'] ?>' ,'<?= $vColetaManual['t_tempoapesqueiro'] ?>', '<?= $vColetaManual['t_distapesqueiro'] ?>', document.getElementById('formEntrevistas'))">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a> 
                </td>
                <td class="td-botao">
                    <a name="Excluir" class="button-del" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['cml_id'] ?>, '<?= $this->url(array("controller" => "coleta-manual", "action" => "deletepesqueiro"), null, true) ?>', <?= $vColetaManual['cml_paf_id'] ?>, 'pesqueiro')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>