<h2>Desembarque -> Conservação do Pescado</h2>
<form method="post">
<fieldset id="dadosEmbarcacao"></fieldset>

    <a id="ancora_conservacao-pescado"></a>
    <fieldset class="noEditable"><legend>Conservação do Pescado:</legend>
        <fieldset class="noEditable"><legend>Adicionar Conservação do Pescado:</legend>
            <div id="base">
                <input type="button" name="Add" class="button-confirm" onclick="jsInsertDynamic(this.form, '<?= $this->url(array("controller" => "conservacao-pescado", "action" => "insert"), null, true) ?>', '<?= $this->url(array("controller" => "conservacao-pescado", "action" => "update"), null, true) ?>')">
                <input type="button" name="Reload" class="button-clear" onclick="jsReloadDynamic(this.form)">

                <input type="text" name="input_valor" placeholder="Conservação Pescado" size="40"  />
                <input readonly="" type="text" name="input_id" />
            </div>
        </fieldset>
        <br>

        <table id="tblPerfil">
            <tr>
                <th width="15%">ID </th>
                <th width="65%">Conservação</th>
                <th width="5%"></th>
                <th width="5%"></th>
            </tr>
            <?php foreach ($this->assignConservacaoPescado as $key => $dados): ?>
                <tr id="rowNumPeril<?= $key ?>">
                    <td><?= $dados['tcp_id'] ?></td>
                    <td><?= $dados['tcp_conserva'] ?></td>
                    <td><input type="button" class="button-edit" width="5%" onclick="jsUpdateDynamic('<?= $dados['tcp_id'] ?>', '<?= $dados['tcp_conserva'] ?>', this.form)"></td>
                    <td><input type="button" class="button-del" width="5%" onclick="jsDeleteDynamic(<?= $dados['tcp_id'] ?>, '<?= $this->url(array("controller" => "conservacao-pescado", "action" => "delete"), null, true) ?>')"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
    <fieldset class="noBorder">
        <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
        <a href="<?= $this->url(array("controller" => "conservacao-pescado", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório - Lista</a>
    </fieldset>
</form>