<h2>Pescador Especialista -> Estrutura Residencial</h2>
<form method="post">
<fieldset id="Especialista"></fieldset>

    <a id="ancora_estrutura-residencia"></a>
    <fieldset class="noEditable"><legend>Estrutura Residencial:</legend>
        <fieldset class="noEditable"><legend>Adicionar Estrutura Residencial:</legend>
            <div id="base">
                <input type="button" name="Add" class="button-confirm" onclick="jsInsertDynamic(this.form, '<?= $this->url(array("controller" => "estrutura-residencia", "action" => "insert"), null, true) ?>', '<?= $this->url(array("controller" => "estrutura-residencia", "action" => "update"), null, true) ?>')">
                <input type="button" name="Reload" class="button-clear" onclick="jsReloadDynamic(this.form)">

                <input type="text" name="input_valor" placeholder="Companhia de Pesca" size="40"  />
                <input readonly="" type="text" name="input_id" />
            </div>
        </fieldset>
        <br>

        <table id="tblPerfil">
            <tr>
                <th width="15%">ID </th>
                <th width="65%">Estrutura Residencial</th>
            </tr>
            <?php foreach ($this->assignEstruturaResidencial as $key => $dadosEstruturaResidencial): ?>
                <tr id="rowNumPeril<?= $key ?>">
                    <td><?= $dadosEstruturaResidencial['terd_id'] ?></td>
                    <td><?= $dadosEstruturaResidencial['terd_estrutura'] ?></td>
                    <td><input type="button" class="button-edit" width="5%" onclick="jsUpdateDynamic('<?= $dadosEstruturaResidencial['terd_id'] ?>', '<?= $dadosEstruturaResidencial['terd_estrutura'] ?>', this.form)"></td>
                    <td><input type="button" class="button-del" width="5%" onclick="jsDeleteDynamic(<?= $dadosEstruturaResidencial['terd_id'] ?>, '<?= $this->url(array("controller" => "estrutura-residencia", "action" => "delete"), null, true) ?>')"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
    <fieldset class="noBorder">
        <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
        <a href="<?= $this->url(array("controller" => "estrutura-residencia", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório - Lista</a>
    </fieldset>
</form>