<div id="titulos">
    <h2>Filogenia->Espécie</h2>
    <h3>Novo</h3>
</div>

<form id="cadastro-usuario" action="<?=$this->url(array("controller"=>"especie","action"=>"criar"),null,true)?>" method="post">
    <fieldset id="Filogenia">
        <div class="esquerda">
         <div class="form-esq">     
            <label for="id" >ID:</label>
            <input type="text" name="id_especie" id="id_especie" placeholder="Id"/><br />
         </div>
         <div class="form-esq">   
            <label for="tipo">Nome:</label>
            <input type="text" id="nome_especie" name="nome_especie" placeholder="Nome"/><br />
         </div>  
         <div class="form-esq">   
            <label for="tipo">Descritor:</label>
            <input type="text" id="descritor_especie" name="descritor_especie" placeholder="Descritor"/><br />
         </div>   
         <div class="form-esq">   
            <label for="tipo">Nome Comum:</label>
            <input type="text" id="nome_comum" name="nome_comum" placeholder="Nome Comum"/><br />
         </div>
         <div class="form-esq">   
            <label for="tipo">Gênero:</label>
              <select name="genero_especie" id="genero_especie">
              <?php
                    foreach ($this->dados as $key => $genero):
               ?>
              
		<option nome="genero_especie" value="<?=$genero['gen_id']?>"><?= $genero['gen_nome']?></option>
              
              <?php
                endforeach;
              ?>
              </select></br>
          </div>  
        <div class="Submit">
            <a href="<?=$this->url(array("controller"=>"especie","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
            <input type="submit" value="Cadastrar" />
        </div>
      </div>      
    </fieldset>
</form>