<div id="espcapturada">
    <table>
        <tr>
        <th>Arte de Pesca </th>
        <th>Espécie</th>
        <th>Quantidade (n)</th>
        <th>Peso (kg)</th>
        <th>Preco</th>
        <th>Número da Entrevista</th>
        </tr>

        <?php foreach ($this->arrayEspArrasto as $key => $entrevista): ?>
            <tr>
            <td>Arrasto de Fundo</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['af_id'] ?></td>
            <td class="td-botao">
                        <a href="<?= $this->url(array("controller" => "arrasto-fundo", "action" => "editar", "id" => $entrevista['af_id']), null, true) ?>">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                            </ul>
                        </a>
                    </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspCalao as $key => $entrevista): ?>
            <tr>
            <td>Calão</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['cal_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "calao", "action" => "editar", "id" => $entrevista['cal_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


        <?php foreach ($this->arrayEspColeta as $key => $entrevista): ?>
            <tr>
            <td>Coleta Manual</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['cml_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "coleta-manual", "action" => "editar", "id" => $entrevista['cml_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspEmalhe as $key => $entrevista): ?>
            <tr>
            <td>Emalhe</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['em_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "emalhe", "action" => "editar", "id" => $entrevista['em_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspGrosseira as $key => $entrevista): ?>
            <tr>
            <td>Groseira/Espinhel</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['grs_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "grosseira", "action" => "editar", "id" => $entrevista['grs_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspJerere as $key => $entrevista): ?>
            <tr>
            <td>Jereré</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['jre_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "jerere", "action" => "editar", "id" => $entrevista['jre_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspLinha as $key => $entrevista): ?>
            <tr>
            <td>Pesca de Linha</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['lin_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "linha", "action" => "editar", "id" => $entrevista['lin_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspLinhaFundo as $key => $entrevista): ?>
            <tr>
            <td>Linha de Fundo</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['lf_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "linha-fundo", "action" => "editar", "id" => $entrevista['lf_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspManzua as $key => $entrevista): ?>
            <tr>
            <td>Manzua</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['man_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "manzua", "action" => "editar", "id" => $entrevista['man_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


        <?php foreach ($this->arrayEspMergulho as $key => $entrevista): ?>
            <tr>
            <td>Mergulho</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['mer_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "mergulho", "action" => "editar", "id" => $entrevista['mer_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspRatoeira as $key => $entrevista): ?>
            <tr>
            <td>Ratoeira</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['rat_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "ratoeira", "action" => "editar", "id" => $entrevista['rat_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


        <?php foreach ($this->arrayEspSiripoia as $key => $entrevista): ?>
            <tr>
            <td>Siripoia</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['sir_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "siripoia", "action" => "editar", "id" => $entrevista['sir_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspTarrafa as $key => $entrevista): ?>
            <tr>
            <td>Tarrafa</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['tar_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "tarrafa", "action" => "editar", "id" => $entrevista['tar_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayEspVaraPesca as $key => $entrevista): ?>
            <tr>
            <td>Vara de Pesca</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['spc_quantidade'] ?></td>
            <td><?= $entrevista['spc_peso_kg'] ?></td>
            <td><?= $entrevista['spc_preco'] ?></td>
            <td><?= $entrevista['vp_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "vara-pesca", "action" => "editar", "id" => $entrevista['vp_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


    </table>
</div>