<h2>Pescador Especialista -> Frequências de Pesca</h2>
<form method="post" id="frequencia-pesca">
<fieldset id="Especialista"></fieldset>

    <a id="ancora_frequencia-pesca"></a>
    <fieldset class="noEditable"><legend>Frequências de Pesca:</legend>
        <fieldset class="noEditable"><legend>Adicionar Frequências de Pesca:</legend>
            <div id="base">
                <input type="button" name="Add" class="busca" value="Adicionar" onclick="jsInsertDynamic(this.form, '<?= $this->url(array("controller" => "frequencia-pesca", "action" => "insert"), null, true) ?>', '<?= $this->url(array("controller" => "frequencia-pesca", "action" => "update"), null, true) ?>')">
                <input type="button" name="Reload" class="busca" value="Limpar campos" onclick="jsReloadDynamic(this.form)">

                <input type="text" name="input_valor" placeholder="Companhia de Pesca" size="40"  />
                <input readonly="" type="text" name="input_id" />
            </div>
        </fieldset>
        <br>

        <table id="tblPerfil">
            <tr>
                <th width="15%">ID </th>
                <th width="85%">Frequências de Pesca</th>
            </tr>
            <?php foreach ($this->assignFrequenciaPesca as $key => $dadosFrequenciaPesca): ?>
                <tr id="rowNumPeril<?= $key ?>">
                    <td><?= $dadosFrequenciaPesca['tfp_id'] ?></td>
                    <td><?= $dadosFrequenciaPesca['tfp_frequencia'] ?></td>
                    <td class="td-botao">
                        <a name="Editar" onclick="jsUpdateDynamic('<?= $dadosFrequenciaPesca['tfp_id'] ?>', '<?= $dadosFrequenciaPesca['tfp_frequencia'] ?>', document.getElementById('frequencia-pesca'))">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                            </ul>
                        </a>
                    </td>
                    <td class="td-botao">
                        <a  name="Excluir"  onclick="jsDeleteDynamic(<?= $dadosFrequenciaPesca['tfp_id'] ?>, '<?= $this->url(array("controller" => "frequencia-pesca", "action" => "delete"), null, true) ?>')">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                            </ul>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
    <fieldset class="noBorder">
        <a href="<?= $this->url(array("controller" => "frequencia-pesca", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório - Lista</a>
    </fieldset>
</form>