<div id="titulos">
    <h2>Relatórios->Gráficos</h2>
</div>
<a href="<?= $this->url(array("controller" => "relatorios", "action" => "pescadoresporto"), null, true) ?>" id="botao-ancora">Pescadores por Porto</a><br/>
<a href="<?= $this->url(array("controller" => "relatorios", "action" => "pescadorescolonia"), null, true) ?>" id="botao-ancora">Pescadores por Colônias</a><br/>
<a href="<?= $this->url(array("controller" => "relatorios", "action" => "pescadoresescolaridade"), null, true) ?>" id="botao-ancora">Pescadores por Escolaridade</a><br/>
<a href="<?= $this->url(array("controller" => "relatorios", "action" => "monitoramentos"), null, true) ?>" id="botao-ancora">Monitoramentos</a><br/>