<html dir="ltr">
    <head>
        <script src="/js/funcoesJquery.js"></script>
    </head>

    <h2>Perfil Social->Comunidade</h2>

    <a href="<?= $this->url(array("controller" => "comunidade", "action" => "novo"), null, true) ?>" id="botao-ancora">Novo</a>
    <fieldset id="dadosSocial"></fieldset>
    <table>
        <tr>
            <th>ID</th>
            <th>Comunidade</th>
        </tr>

        <?php
        foreach ($this->dados as $key => $comunidade):
            ?>
            <tr>
                <td><?= $comunidade['tcom_id'] ?></td>
                <td><?= $comunidade['tcom_nome'] ?></td>
                <td class="td-botao">
                    <a href="<?= $this->url(array("controller" => "comunidade", "action" => "editar", "id" => $comunidade['tcom_id']), null, true) ?>">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a>
                </td>
                
                 <td class="td-botao">
                    <a value="Excluir" onclick="beforeDelete('<?= $this->url(array("controller" => "comunidade", "action" => "excluir", "id" =>  $comunidade['tcom_id']), null, true) ?>')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                        
                 </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <br/><br/>
    <a href="<?= $this->url(array("controller" => "comunidade", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
</html>