<div class="menu-relatorios">
    <a href="#">
        <img src="img/pescador-icon.jpg"/>
        <span class="legenda">Pescadores  </span>
    </a>
</div>

<div class="menu-relatorios">
    <a href="#">
        <img src="img/peixe-icon.jpg"/>
        <span class="legenda">Espécies</span>
    </a>
</div>

<div class="menu-relatorios">
    <a href="#">
        <img src="img/barco-icon.jpg"/>
        <span class="legenda">Embarcações</span>
    </a>
</div>

<div class="menu-relatorios">
    <a href="#">
        <img src="img/entrevista-icon.jpg"/>
        <span class="legenda">Entrevistas</span>

    </a>
</div>