<h3>Relatórios -> Principais:</h3>

<div class="menu-relatorios">
    <a class="link-rel" href="<?= $this->url(array("controller" => "pescador", "action" => "relatorio"), null, true) ?>">
        <img src="img/pescador-icon.png"/><br/>
        <span class="legenda">Pescadores  </span>
    </a>
</div>

<div class="menu-relatorios">
    <a class="link-rel" href="<?= $this->url(array("controller" => "especie", "action" => "indexrelatorio"), null, true) ?>">
        <img src="img/peixe-icon.png"/> <br/>
        <span class="legenda">Espécies</span>
    </a>
</div>

<div class="menu-relatorios">
    <a class="link-rel" href="<?= $this->url(array("controller" => "barcos", "action" => "indexrelatorio"), null, true) ?>">
        <img src="img/barco-icon.png"/><br/>
        <span class="legenda">Embarcações</span>
    </a>
</div>

<div class="menu-relatorios">
    <a class="link-rel" href="<?= $this->url(array("controller" => "relatorios", "action" => "index"), null, true) ?>">
        <img src="img/entrevista-icon.png"/><br/>
        <span class="legenda">Entrevistas</span>
    </a>
</div>

<div class="menu-relatorios">
    <a class="link-rel" href="<?= $this->url(array("controller" => "porto", "action" => "relatorioindex"), null, true) ?>">
        <img src="img/porto-icon.png"/><br/>
        <span class="legenda">Portos</span>
    </a>
</div>

<div class="menu-relatorios">
    <a class="link-rel" href="<?= $this->url(array("controller" => "estatistica", "action" => "index"), null, true) ?>">
        <img src="img/estatistica-icon.png"/><br/>
        <span class="legenda">Estatísticos</span>
    </a>
</div>