<div id="Renda">
    <h2>Social->Renda</h2>
    <h3>Novo</h3>
</div>

<form action="<?= $this->url(array("controller" => "Renda", "action" => "criar"), null, true) ?>" method="post">
    <fieldset id="dadosSocial">
        <div class="esquerda">
            <div class="form-esq">
                <label>Código: </label>
                <input type="text" readonly="" size="5" name="idRenda" placeholder="Código Renda (Automático)"/>
            </div>

            <div class="form-esq">
                <label>Renda: </label>
                <input type="text" name="renRenda" placeholder="Renda"/> <br />
            </div>


            <div class="form-esq">
                <label>Fator Mínimo: </label>
                <input type="number" min="0.0"  step="0.5" name="renFatorMin" placeholder="Fator Multiplicador da Renda"/> <br />
            </div>

            <div class="form-esq">
                <label>Fator Máximo: </label>
                <input type="number" min="0.0"  step="0.5" name="renFatorMax" placeholder="Fator Multiplicador da Renda"/> <br />
            </div>

            <div class="Submit">
                <a href="<?= $this->url(array("controller" => "Renda", "action" => "index"), null, true) ?>" id="botao-ancora">Voltar</a>
                <input type="submit" value="Cadastrar" />
            </div>
        </div>
    </fieldset>
</form>