<div id="avistamento">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Avistamentos:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="15%">Id Avistamento</th>
            <th width="85%">Avistamento</th>
            </tr>
            <?php
            foreach ($this->vRatoeiraAvistamento as $key => $vRatoeiraAvistamento):
                ?>
                <tr id="itemRatoeiraRows">
                <td name="inputIdEntrevista"> <?= $vRatoeiraAvistamento['avs_id'] ?> </td>
                <td name="inputAvistamento" > <?= $vRatoeiraAvistamento['avs_descricao'] ?> </td>
                <td class="td-botao">
                    <a name="Excluir" class="button-del" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['rat_id'] ?>, '<?= $this->url(array("controller" => "ratoeira", "action" => "deleteavistamento"), null, true) ?>', <?= $vRatoeiraAvistamento['avs_id'] ?>, 'avistamento')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>