<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="5%">Id Entrevista</th>
            <th width="50%">Pesqueiro</th>
            <th width="30%">Tempo até o Pesqueiro</th>
            <th width="30%">Distância até o Pesqueiro</th>
            </tr>
            <?php
            foreach ($this->vRatoeira as $key => $vRatoeira):
                ?>
                <tr id="itemRatoeiraRows">
                <td name="inputIdEntrevista"> <?= $vRatoeira['rat_id'] ?> </td>
                <td name="inputPesqueiro" > <?= $vRatoeira['paf_pesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vRatoeira['t_tempoapesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vRatoeira['t_distapesqueiro'] ?> </td>
                <td class="td-botao">
                    <a name="Editar" class="button-del" onclick="ajax_update_pesqueiro('<?= $vRatoeira['rat_paf_id'] ?>','<?= $vRatoeira['paf_id'] ?>', '<?= $vRatoeira['t_tempoapesqueiro'] ?>', '<?= $vRatoeira['t_distapesqueiro'] ?>', document.getElementById('formEntrevistas'))">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a> 
                </td>
                <td class="td-botao">
                    <a name="Excluir" class="button-del" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['rat_id'] ?>, '<?= $this->url(array("controller" => "ratoeira", "action" => "deletepesqueiro"), null, true) ?>', <?= $vRatoeira['rat_paf_id'] ?>, 'pesqueiro')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>