<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="5%">Id Entrevista</th>
            <th width="50%">Pesqueiro</th>
            <th width="30%">Tempo até o Pesqueiro</th>
            <th width="30%">Distância até o Pesqueiro</th>
            </tr>
            <?php
            foreach ($this->vRatoeira as $key => $vRatoeira):
                ?>
                <tr id="itemRatoeiraRows">
                <td name="inputIdEntrevista"> <?= $vRatoeira['rat_id'] ?> </td>
                <td name="inputPesqueiro" > <?= $vRatoeira['paf_pesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vRatoeira['t_tempoapesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vRatoeira['t_distapesqueiro'] ?> </td>
                <td><input type="button" class="button-del" width="5%" onclick="jsDeletePesqueiro(<?= $this->entrevista['rat_id'] ?>, '<?= $this->url(array("controller" => "ratoeira", "action" => "deletepesqueiro"), null, true) ?>', <?= $vRatoeira['rat_paf_id'] ?>)"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>