<div id="especie">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Espécies Capturadas:</legend>
        <table id="especiesCapturadas">
            <tr>
            <th width="17%">Id Entrevista</th>
            <th width="17%">Espécie Capturada</th>
            <th width="17%">Quantidade</th>
            <th width="17%">Peso por tipo de venda</th>
            <th width="17%">Preço por tipo de venda</th>
            <th width="17%">Tipo de venda</th>
            </tr>
            <?php
            foreach ($this->vEspecieCapturadas as $key => $vEspecieCapturada):
                ?>
                <tr id="itemEmbarcacoesRows">
                <td name="inputEntrevista"> <?= $vEspecieCapturada['rat_id'] ?> </td>
                <td name="inputEspecie" > <?= $vEspecieCapturada['esp_nome_comum'] ?> </td>
                <td name="inputQuantidade"> <?= $vEspecieCapturada['spc_quantidade'] . ' Unidades' ?> </td>
                <td name="inputPeso"> <?= $vEspecieCapturada['spc_peso_kg'] . ' kg' ?> </td>
                <td name="inputPreco"> <?= 'R$ ' . $vEspecieCapturada['spc_preco'] ?> </td>>
                <td name="inputMedida"> <?= $vEspecieCapturada['ttv_tipovenda'] ?> </td>
                <td class="td-botao">
                    <a name="Excluir" class="button-del" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['rat_id'] ?>, '<?= $this->url(array("controller" => "ratoeira", "action" => "deletespecie"), null, true) ?>', <?= $vEspecieCapturada['spc_rat_id'] ?>, 'especie')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>