
    <h2>Perfil Social->Programa Social</h2>

    <a href="<?= $this->url(array("controller" => "programa-social", "action" => "novo"), null, true) ?>" id="botao-ancora">Novo</a>
    <fieldset id="dadosSocial"></fieldset>
    <table>
        <tr>
            <th>ID</th>
            <th>Programa Social</th>
        </tr>

        <?php foreach ($this->programasSocial as $key => $programaSocial): ?>
            <tr>
                <td><?= $programaSocial['prs_id'] ?></td>
                <td><?= $programaSocial['prs_programa'] ?></td>

                <td class="td-botao">
                    <a href="<?= $this->url(array("controller" => "programa-social", "action" => "editar", "id" => $programaSocial['prs_id']), null, true) ?>">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a>
                </td>

                <td class="td-botao">
                    <a href="<?= $this->url(array("controller" => "programa-social", "action" => "excluir", "id" => $programaSocial['prs_id']), null, true) ?>">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-trash"></span></li>
                        </ul>
                    </a>
                </td>

            </tr>
        <?php endforeach; ?>
    </table>
    <br/><br/>
    <a href="<?= $this->url(array("controller" => "programa-social", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
