<form method="post">
    <fieldset id="dadosDesembarque"></fieldset>

    <a id="ancora_destinopescado"></a>
    <fieldset class="noEditable"><legend>Destino do Pescado:</legend>
        <fieldset class="noEditable"><legend>Adicionar Destino do Pescado:</legend>
            <div id="base">
                <input type="button" name="Add" class="button-confirm" onclick="jsInsertDestinoPescado(this.form, '<?= $this->url(array("controller" => "destino-pescado", "action" => "insert"), null, true) ?>')">
                <input type="button" name="Reload" class="button-clear" onclick="jsReloadDestinoPescado(this.form)">

                <input type="text" name="inputdp_destino" placeholder="Destino do Pescado" size="40"  />
                <input readonly="" type="text" name="inputdp_id" />
            </div>
        </fieldset>
        <br>

        <table id="tblDestinoPescado">
            <tr>
                <th width="15%">ID </th>
                <th width="65%">Perfil</th>
                <th width="5%"></th>
                <th width="5%"></th>
            </tr>
            <?php foreach ($this->assignDestinoPescado as $key => $dadosDestinoPescado): ?>
                <tr id="rowNumDestinoPescado<?= $key ?>">
                    <td><?= $dadosDestinoPescado['dp_id'] ?></td>
                    <td><?= $dadosDestinoPescado['dp_destino'] ?></td>
                    <td><input type="button" class="button-edit" width="5%" onclick="jsUpdateDestinoPescado('<?= $dadosDestinoPescado['dp_id'] ?>', '<?= $dadosDestinoPescado['dp_destino'] ?>', this.form)"></td>
                    <td><input type="button" class="button-del" width="5%" onclick="jsDeleteDestinoPescado(<?= $dadosDestinoPescado['dp_id'] ?>, '<?= $this->url(array("controller" => "destino-pescado", "action" => "delete"), null, true) ?>')"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
    <fieldset class="noBorder">
		<a href="<?= $this->url(array("controller" => "destino-pescado", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
        <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
    </fieldset>
</form>