<div id="titulos">
    <h2>Desembarque->Área de Pesca</h2>
    <h3>Novo</h3>
</div>

<form action="<?=$this->url(array("controller"=>"mare","action"=>"criar"),null,true)?>" method="post">
    <fieldset id="dadosDesembarque">
        <div class="esquerda">
            <div class="form-esq">
                <label>Tipo de Maré: </label>
                <input type="text" placeholder="Tipo de Maré" name="mare" /> <br/>
            </div>
        <div class="Submit">
            <a href="<?=$this->url(array("controller"=>"mare","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
            <input type="submit" value="Cadastrar" />
        </div> 
        </div>
    </fieldset>
</form>