<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
                <table id="pesqueiros">
                    <tr>
                        <th width="15%">Id Entrevista</th>
                        <th width="85%">Pesqueiro</th>
                    </tr>
                    <?php
                    foreach ($this->vCalao as $key => $vCalao):
                        ?>
                        <tr id="itemArrastoRows">
                            <td name="inputIdEntrevista"> <?= $vCalao['cal_id'] ?> </td>
                            <td name="inputPesqueiro"> <?= $vCalao['paf_pesqueiro'] ?> </td>
                            <td class="td-botao">
                                <a name="Editar" class="button-del" onclick="ajax_update_pesqueiro('<?= $vCalao['cal_paf_id'] ?>','<?= $vCalao['paf_id'] ?>', '', '','', document.getElementById('formEntrevistas'))">
                                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                                    </ul>
                                </a> 
                            </td>
                            <td class="td-botao">
                                <a name="Excluir" class="button-del" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['cal_id'] ?>, '<?= $this->url(array("controller" => "calao", "action" => "deletepesqueiro"), null, true) ?>', <?= $vCalao['cal_paf_id'] ?>, 'pesqueiro')">
                                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                                        <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                                    </ul>
                                </a> 
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
    </fieldset>
</div>