<div id="titulos">
    <h2>Desembarque->Vento</h2>
    <h3>Novo</h3>
</div>


<form action="<?=$this->url(array("controller"=>"vento","action"=>"criar"),null,true)?>" method="post">
    <fieldset id="dadosDesembarque">
     <div class="esquerda">
      <div class="form-esq">  
        <input type="hidden" name="idVento" />
        <label>Vento: </label>
        <input type="text" name="vento" placeholder="Vento"/> <br />
       </div>
        <div class="Submit">
            <a href="<?=$this->url(array("controller"=>"vento","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
            <input type="submit" value="Cadastrar" />
        </div> 
    </div>
    </fieldset>
</form>