

<h2>Perfil Social-> Colônias</h2>

<a href="<?= $this->url(array("controller" => "colonia", "action" => "novo"), null, true) ?>" id="botao-ancora">Novo</a>
<fieldset id="dadosSocial"></fieldset>
<table>
    <tr>
        <th>ID</th>
        <th>Colonia</th>
    </tr>

    <?php
    foreach ($this->dados as $key => $colonia):
        ?>
        <tr>
            <td><?= $colonia['tc_id'] ?></td>
            <td><?= $colonia['tc_nome'] ?></td>

            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "colonia", "action" => "visualizar", "id" => $colonia['tc_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Visualizar"><span class="ui-icon ui-icon-search"></span></li>
                    </ul>
                </a>
            </td>

            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "colonia", "action" => "editar", "id" => $colonia['tc_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>

            <td class="td-botao">
                <a value="Excluir" onclick="beforeDelete('<?= $this->url(array("controller" => "colonia", "action" => "excluir", "id" => $colonia['tc_id']), null, true) ?>')">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                </a> 
            </td>

        </tr>
    <?php endforeach; ?>
</table>
<br/><br/>
<a href="<?= $this->url(array("controller" => "colonia", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
