<div id="titulos">
    <h2>Perfil Social->Colonia</h2>
    <h3>Visualizar</h3>
</div>

<fieldset id="dadosSocial">
<table>
    <tr>
        <th>Colonia</th>
        <th>Comunidade</th>
        <th>Especificidade</th>
        <th>Logradouro</th>
        <th>Número</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th>CEP</th>
        <th>Complemento</th> 
    </tr>
    <tr>
        <td><?= $this->colonia['TC_Nome'] ?></td>
        <td><?= $this->colonia['TCOM_NOME'] ?></td>
        <td><?= $this->colonia['TC_Especificidade'] ?></td>
        <td><?= $this->colonia['TE_Logradouro'] ?></td>
        <td><?= $this->colonia['TE_Numero'] ?></td>
        <td><?= $this->colonia['TE_Bairro'] ?></td>
        <td><?= $this->colonia['TMun_Municipio'] ?></td>
        <td><?= $this->colonia['TUF_Sigla'] ?></td>
        <td><?= $this->colonia['TE_CEP'] ?></td>
        <td><?= $this->colonia['TE_Comp'] ?></td>
    </tr>
     
</table>
    <div id="Submit-esq">
        <a href="<?=$this->url(array("controller"=>"colonia","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
    </div>
</fieldset>