<div id="titulos">
    <h2>Perfil Social->Colonia</h2>
    <h3>Visualizar</h3>
</div>

<fieldset id="dadosSocial">
<table>
    <tr>
        <th>Colonia</th>
        <th>Especificidade</th>
        <th>Logradouro</th>
        <th>Número</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th>CEP</th>
        <th>Complemento</th> 
    </tr>
    <tr>
        <td><?= $this->colonia['tc_nome'] ?></td>
        <td><?= $this->colonia['tc_especificidade'] ?></td>
        <td><?= $this->colonia['te_logradouro'] ?></td>
        <td><?= $this->colonia['te_numero'] ?></td>
        <td><?= $this->colonia['te_bairro'] ?></td>
        <td><?= $this->colonia['tmun_municipio'] ?></td>
        <td><?= $this->colonia['tuf_sigla'] ?></td>
        <td><?= $this->colonia['te_cep'] ?></td>
        <td><?= $this->colonia['te_comp'] ?></td>
    </tr>
     
</table>
    <div id="Submit-esq">
        <a href="<?=$this->url(array("controller"=>"colonia","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
    </div>
</fieldset>