<div id="titulos">
    <h2>Desembarque->Pesca com Vara</h2>
    <h3>Entrevista</h3>
</div>

<div class="esquerda-entrevista">
    <form action="<?= $this->url(array("controller" => "vara-pesca", "action" => "atualizar"), null, true) ?>" name="entrevista" onSubmit="return verificaData()">
        <fieldset id="Entrevista">
        <div class="esquerda">
                <div class="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" disabled="true" value="<?= $this->monitoramento['fd_id'] ?>" /><br />
                </div>
                <div class="form-esq">
                    <label>ID monitoramento:</label>
                    <input type="text" name="id_monitoramento" placeholder="ID"  value="<?= $this->monitoramento['mnt_id'] ?>" /><br />
                </div>
                <div class="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" placeholder = "ID" name="id_entrevista" disabled="true" value="<?= $this->entrevista['vp_id'] ?>"/><br />
                </div>
            </div>
            <br/>
            <div class="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div class="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox"  name="embarcada" <?php if($this->entrevista['vp_embarcada'] === true){ echo 'checked';} else{ echo '';}?>/><br />
                </div>
                <div class="form-esq">
                    <label>Motor?</label>
                    <input type="checkbox"  name="motor" <?php if($this->entrevista['vp_motor'] === true){ echo 'checked';} else{ echo '';} ?>/><br />
                </div>
                <div class="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco" placeholder="Nome do Barco" />
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>" <?=( $barco['bar_id'] == $this->entrevista['bar_id'])? 'selected="selected"': '';?>><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>

                </div>
                <div class="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" />
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>" <?=( $tipoEmbarcacao['tte_id'] == $this->entrevista['tte_id'])? 'selected="selected"': '';?>><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>

                </div>
            </div>    
            <div class="direita-entrevista">
                <div class="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="pescadorEntrevistado" />
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>" <?=( $pescador['tp_id'] == $this->entrevista['tp_id_entrevistado'])? 'selected="selected"': '';?>><?= $pescador['tp_nome'] .' ( '. $pescador['tp_apelido']. ' )' ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select><br />
                </div>
                <div class="form-esq">
                    <label>Qtd de Pescadores:</label>
                    <input type="text"  name="numPescadores" min="1" placeholder="Quantidade de Pescadores " value="<?=$this->entrevista['vp_quantpescadores']?>"/><br />
                </div>
            </div>
            <div class="esquerda">
                <legend><h4>Saída e Volta:</h4></legend>
                <div class="form-esq">

                    <label>Data:</label>
                    <input type="date" name="dataSaida" min="2013-11-01" placeholder="Data da Saída" value="<?=$this->dataSaida ?>"/>
                </div>
                <div class="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaSaida" placeholder="Hora da Saída" value="<?=$this->horaSaida ?>"/>
                </div>
            </div>
            <div class="direita-entrevista">
                <div class="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataVolta" min="2013-11-01" placeholder="Data da Volta" value="<?=$this->dataVolta ?>"/>
                </div>
                <div class="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaVolta" placeholder="Hora da Volta" value="<?=$this->horaVolta ?>"/>
                </div>
            </div>
            <br/>
            <div class="esquerda">
                <div class="form-esq">
                    <label>Tempo Gasto:</label>
                    <input type="time" name="tempoGasto" placeholder="Data da Saída" value="<?=$this->entrevista['vp_tempogasto']?>"/>
                </div>
            </div>    
            <div class="esquerda">
                <div class="form-esq">
                    <legend><h4>Gastos:</h4></legend>
                    <label>Diesel(L):</label>
                    <input type="text"  name="diesel" placeholder="Diesel" value="<?=$this->entrevista['vp_diesel']?>"/>
                </div>
                <div class="form-dir">    
                    <label>Óleo(L):</label>
                    <input type="text"  name="oleo" placeholder="Óleo" value="<?=$this->entrevista['vp_oleo']?>"/><br />
                </div>
            </div>
            <div class="direita-entrevista">
                <div class="form-dir">    
                    <label>Alimento($):</label>
                    <input type="text"  name="alimento" placeholder="Alimento" value="<?=$this->entrevista['vp_alimento']?>"/><br />
                </div>
                <div class="form-dir">    
                    <label>Gelo($):</label>
                    <input type="text"  name="gelo" placeholder="Gelo" value="<?=$this->entrevista['vp_gelo']?>"/><br />
                </div>
            </div>
            <br/>
            <div class="esquerda">
                <div class="form-esq">
                    <legend><h4>Maré:</h4></legend>
                    <label>Tipo:</label>
                    <select name="mare" >
                        <?php
                        foreach ($this->mare as $key => $mare):
                            ?>
                            <option value="<?= $mare['mre_id'] ?>" <?=( $mare['mre_id'] == $this->entrevista['mre_id'])? 'selected="selected"': '';?>><?= $mare['mre_tipo'] ?></option>
                            <?php
                        endforeach;
                        ?>
                    </select>
                </div>   
                <div class="form-dir">    
                    <label>Maré Viva?</label>
                    <input type="checkbox" name="mareviva"  <?php if($this->entrevista['vp_mreviva'] === true){ echo 'checked';} else{ echo '';}?>>
                </div>   
            </div><br/>
            <div class="esquerda">
                <div class="form-esq">
                    <legend><h4>Esforço:</h4></legend>
                    <label>Número de Linhas:</label>
                    <input type="text" name="numLinhas" placeholder="Linhas" value="<?=$this->entrevista['vp_numlinhas']?>"/>
                </div>
                <div class="form-dir">    
                    <label> Anzóis p/ Linha:</label>
                    <input type="text" name="numAnzois" placeholder="Anzóis P/ Linha" value="<?=$this->entrevista['vp_numanzoisplinha']?>"/><br />
                </div>
            </div>
            <div class="direita-entrevista">
                <div class="form-dir">    
                    <label>Isca:</label>
                    <select name="isca" />
                    <?php
                    foreach ($this->iscas as $key => $isca):
                        ?>
                        <option value="<?= $isca['isc_id'] ?>" <?=( $isca['isc_id'] == $this->entrevista['isc_id'])? 'selected="selected"': '';?>><?= $isca['isc_tipo'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
            </div><br/>
            <div class="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div class="form-esq">    
                    <label>Destino do Pescado:</label>
                    <select name="destinoPescado" />
                    <?php
                    foreach ($this->destinos as $key => $destino):
                        ?>
                        <option value="<?= $destino['dp_id'] ?>" <?=( $destino['dp_id'] == $this->entrevista['dp_id'])? 'selected="selected"': '';?>><?= $destino['dp_destino'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                </div>
                <div class="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" name="subamostra" <?php if($this->entrevista['vp_subamostra'] === true){ echo 'checked';} else{ echo '';}?>/><br />
                </div>
                <div class="form-esq">
                    <label for="tipo">Observacao:</label>
                    <input type="text" name="observacao" placeholder="Observação" value="<?=$this->entrevista['vp_obs']?>"/><br />
                </div>
                <input type="hidden" name="id_entrevista"value="<?= $this->entrevista['vp_id'] ?>"/><br />
                <input type="hidden" name="id_fichaDiaria" value="<?= $this->monitoramento['fd_id'] ?>" /><br />
                <div class="Submit">
                    <input type="submit" value="Salvar Alterações"/>
                </div>
            </div>
        </fieldset>
    </form>
    <form>
        <input type="hidden" placeholder = "ID" name="id_entrevista"  value="<?= $this->entrevista['vp_id'] ?>"/><br />
        <input type="hidden" name="id_monitoramento" placeholder="ID"  value="<?= $this->entrevista['mnt_id'] ?>" /><br />
        <input type="hidden" name="id_fichaDiaria" placeholder="ID"  value="<?= $this->monitoramento['fd_id'] ?>" /><br />
       
    <fieldset class="noEditable"><legend>Pesqueiro:</legend>
                <fieldset class="noEditable"><legend>Pesqueiro e tempo até o pesqueiro:</legend>
                    <div id="base">
                        <input onclick="jsInsertPesqueiroWithTimeAndRange(this.form, '<?= $this->url(array("controller" => "vara-pesca", "action" => "insertpesqueiro"), null, true) ?>', '<?= $this->entrevista['vp_id'] ?>')" type="button" value="Adicionar" />
                        <select style="float:left;" name="nomePesqueiro" class="responsivo">
                            <option value="" selected></option>
                            <?php foreach ($this->pesqueiros as $key => $pesqueiro): ?>
                                <option value="<?= $pesqueiro['paf_id']; ?>"><?= $pesqueiro['paf_pesqueiro']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <input style="float:left;" class="responsivo" type="time" name="tempoAPesqueiro" placeholder="Tempo Até pesqueiro" size="10px"/>
                        <input style="float:left;" class="responsivo" type="number" name="distAPesqueiro" placeholder="Distância Até pesqueiro (km)" size="23px"/>

                    </div>

                </fieldset>
                <br>
                <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
                    <table id="pesqueiros">
                        <tr>
                            <th width="5%">Id Entrevista</th>
                            <th width="50%">Pesqueiro</th>
                            <th width="30%">Tempo até o Pesqueiro</th>
                            <th width="30%">Distância até o Pesqueiro</th>
                        </tr>
                        <?php
                        foreach ($this->vVaraPesca as $key => $vVarapesca):
                            ?>
                            <tr id="itemVaraPescaRows">
                                <td name="inputIdEntrevista"> <?= $vVarapesca['vp_id'] ?> </td>
                                <td name="inputPesqueiro" > <?= $vVarapesca['paf_pesqueiro'] ?> </td>
                                <td name="inputTempoaPesqueiro"> <?= $vVarapesca['t_tempoapesqueiro'] ?> </td>
                                <td name="inputTempoaPesqueiro"> <?= $vVarapesca['t_distapesqueiro'] ?> </td>
                                <td><input type="button" class="button-del" width="5%" onclick="jsDeletePesqueiro(<?= $this->entrevista['vp_id'] ?>, '<?= $this->url(array("controller" => "vara-pesca", "action" => "deletepesqueiro"), null, true) ?>', <?= $vVarapesca['vp_paf_id'] ?>)"></td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </fieldset>
            </fieldset>
<fieldset class="noEditable"><legend>Espécies Capturadas:</legend>
        <fieldset class="noEditable"><legend>Dados das Espécies Capturadas:</legend>

            <div id="base">
                <input class="responsivo" onclick="jsInsertEspecieCapturadaTipoVenda(this.form, '<?= $this->url(array("controller" => "vara-pesca", "action" => "insertespeciecapturada"), null, true) ?>','<?=$this->entrevista['vp_id']?>')" type="button" value="Adicionar" />
                <select style="float:left;" name="SelectEspecie" class="responsivo" >
                    <option value="" selected></option>
                    <?php foreach ($this->especies as $key => $especie): ?>
                        <option value="<?= $especie['esp_id']; ?>"><?= $especie['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <input class="responsivo" style="float:left;" type="text" name="quantidade" placeholder="Quantidade" size="10px">
                <input class="responsivo" style="float:left;" type="text" name="peso" placeholder="Peso" size="10px">
                <input class="responsivo" style="float:left;" type="text" name="precokg" placeholder="Preço por kg" size="10px">
                <select name="tipoVenda" class="espc" class="responsivo">
                    <option value="" selected></option>
                     <?php foreach ($this->tipovenda as $key => $tipovenda): ?>
                        <option value="<?= $tipovenda['ttv_id']?>"><?= $tipovenda['ttv_tipovenda']; ?></option>
                     <?php endforeach; ?>
                </select>
                <input class="responsivo" type="hidden" name="id_entrevista"  value="<?= $this->entrevista['vp_id'] ?>"/>

            </div>

        </fieldset>
        <br>
         <fieldset class="noEditable" id="itemArteTipoRows"><legend>Espécies Capturadas:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        <th width="20%">Id Entrevista</th>
                        <th width="30%">Espécie Capturada</th>
                        <th width="20%">Quantidade</th>
                        <th width="20%">Peso (kg)</th>
                        <th width="20%">Preço por kg</th>
                    </tr>
                    <?php
                    foreach ($this->vEspecieCapturadas as $key => $vEspecieCapturada):
                        ?>
                        <tr id="itemEmbarcacoesRows">
                            <td name="inputEntrevista"> <?= $vEspecieCapturada['vp_id'] ?> </td>
                            <td name="inputEspecie" > <?= $vEspecieCapturada['esp_nome_comum'] ?> </td>
                            <td name="inputQuantidade"> <?= $vEspecieCapturada['spc_quantidade'] ?> </td>
                            <td name="inputPeso"> <?= $vEspecieCapturada['spc_peso_kg'] ?> </td>
                            <td name="inputPreco"> <?= $vEspecieCapturada['spc_preco'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" 
                            onclick="jsDeleteEspecieCapturada(<?= $this->entrevista['vp_id'] ?>, '<?= $this->url(array("controller" => "vara-pesca", "action" => "deletespecie"), null, true) ?>', <?= $vEspecieCapturada['spc_vp_id'] ?>)"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
    </fieldset>
    <fieldset class="noEditable"><legend>Avistamento:</legend>
        <fieldset class="noEditable"><legend>O Que foi avistado:</legend>
            <div id="base">
                <input onclick="jsInsertAvistamento(this.form, '<?= $this->url(array("controller" => "vara-pesca", "action" => "insertavistamento"), null, true) ?>', '<?=$this->entrevista['vp_id']?>')" type="button" value="Adicionar" />
                
                <select style="float:left;" name="SelectAvistamento">
                    <option value="" selected></option>
                    <?php foreach ($this->avistamentos as $key => $avistamento): ?>
                        <option value="<?= $avistamento['avs_id']; ?>"><?= $avistamento['avs_descricao']; ?></option>
                    <?php endforeach; ?>
                </select>
                
            </div>

        </fieldset>
        <br>
        <fieldset class="noEditable" id="itemArteTipoRows"><legend>Avistamentos:</legend>
            <table id="pesqueiros">
                <tr>
                    <th width="5%">Id Avistamento</th>
                    <th width="50%">Avistamento</th>
                </tr>
                <?php
                foreach ($this->vVaraPescaAvistamento as $key => $vVaraPescaAvistamento):
                    ?>
                    <tr id="itemVaraPescaRows">
                        <td name="inputIdEntrevista"> <?= $vVaraPescaAvistamento['avs_id'] ?> </td>
                        <td name="inputAvistamento" > <?= $vVaraPescaAvistamento['avs_descricao'] ?> </td>
                        <td><input type="button" class="button-del" width="5%" onclick="jsDeleteAvistamento(<?= $this->entrevista['vp_id'] ?>, '<?= $this->url(array("controller" => "vara-pesca", "action" => "deleteavistamento"), null, true) ?>', <?= $vVaraPescaAvistamento['avs_id'] ?>)"></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </fieldset>
    </fieldset>
    <!--////////////////////////////////////////////////////////AMOSTRAGEM PEIXES///////////////////////////////////////////////////////////-->
    <fieldset class="noEditable"><legend>Amostras de Peixes:</legend>
        <fieldset class="noEditable"><legend>Dados das Amostras:</legend>

            <div id="base_peixe">
                <input class="responsivo" onclick="jsInsertAmostraPeixe(this.form, '<?= $this->url(array("controller" => "vara-pesca", "action" => "insertbiopeixe"), null, true) ?>','<?=$this->entrevista['vp_id']?>')" type="button" value="Adicionar" />
                
                <select style="float:left;" name="SelectEspeciePeixe" class="responsivo">
                    <?php foreach ($this->especies as $key => $especie): ?>
                        <option value="<?= $especie['esp_id']; ?>"><?= $especie['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <input class="responsivo" style="float:left;" type="text" name="comprimentoPeixe" placeholder="Comprimento" size="10px">

                <select class="responsivo" style="float:left;" class="amostragem" name="SelectSexoPeixe" style="width:5px">
                    <option value="M">Macho</option>
                    <option value="F">Fêmea</option>
                    <option value="I">Indefinido</option>
                </select>
                
                <input class="responsivo" style="float:left;" type="text" name="pesoPeixe" placeholder="Peso" size="10px">

                
            </div>

        </fieldset>
        <br>
         <fieldset class="noEditable" id="itemArteTipoRows"><legend>Dados Cadastrados:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        
                        <th width="20%">Id Amostra</th>
                        <th width="20%">Espécie</th>
                        <th width="20%">Comprimento</th>
                        <th width="10%">Sexo</th>
                        <th width="20%">Peso</th>
                    </tr>
                    <?php
                    foreach ($this->vBioPeixe as $key => $unidadePeixe):
                        ?>
                        <tr id="itemEmbarcacoesRows">
                            
                            <td name="inputAmostra"> <?= $unidadePeixe['tvpbp_id'] ?> </td>
                            <td name="inputMaturidade"> <?= $unidadePeixe['esp_nome_comum'] ?> </td>
                            <td name="inputComp.Cabeca"> <?= $unidadePeixe['tbp_comprimento'] ?> </td>
                            <td name="inputSexo"> <?= $unidadePeixe['tbp_sexo'] ?> </td>
                            <td name="inputPeso"> <?= $unidadePeixe['tbp_peso'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeleteUnidade('<?= $this->url(array("controller" => "vara-pesca", "action" => "deletebiopeixe"), null, true) ?>', '<?=$this->entrevista['vp_id']?>','<?= $unidadePeixe['tvpbp_id'] ?>', '#base_peixe')"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
        </fieldset>
<!--////////////////////////////////////////////////////////AMOSTRAGEM PEIXES///////////////////////////////////////////////////////////-->
        <fieldset class="noEditable"><legend>Amostras de Camarão:</legend>
        <fieldset class="noEditable"><legend>Dados das Amostras:</legend>

            <div id="base_camarao">
                <input class="responsivo" onclick="jsInsertAmostraCamarao(this.form, '<?= $this->url(array("controller" => "vara-pesca", "action" => "insertbiocamarao"), null, true) ?>','<?=$this->entrevista['vp_id']?>')" type="button" value="Adicionar" />
                
                <select class="responsivo" style="float:left;" name="SelectEspecieCamarao">
                    <?php foreach ($this->especieCamarao as $key => $especieCamarao): ?>
                        <option value="<?= $especieCamarao['esp_id']; ?>"><?= $especieCamarao['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <select class="responsivo" style="float:left;" class="amostragem" name="SelectSexoCamarao" >
                    <option value="M">Macho</option>
                    <option value="F">Fêmea</option>
                    <option value="I">Indefinido</option>
                </select>
                <select class="responsivo" style="float:left;" class="amostragem" name="SelectMaturidade">
                    <?php foreach ($this->maturidade as $key => $maturidade): ?>
                        <option value="<?= $maturidade['tmat_id']; ?>"><?= $maturidade['tmat_tipo']; ?></option>
                    <?php endforeach; ?>
                </select>
                
                <input class="responsivo" style="float:left;" type="text" name="comprimentoCabeca" placeholder="Comp. Carapaça" size="10px">

                <input class="responsivo" style="float:left;" type="text" name="pesoCamarao" placeholder="Peso" size="10px">


            </div>

        </fieldset>
        <br>
         <fieldset class="noEditable" id="itemArteTipoRows"><legend>Dados Cadastrados:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        
                        <th width="20%">Id Amostra</th>
                        <th width='20%'>Espécie</th>
                        <th width="10%">Sexo</th>
                        <th width="20%">Maturidade</th>
                        <th width="20%">Comp.Carapaça</th>
                        <th width="20%">Peso</th>
                    </tr>
                    <?php
                    foreach ($this->vBioCamarao as $key => $unidadeCamarao):
                        ?>
                        <tr id="itemEmbarcacoesRows">
                            
                            <td name="inputAmostra"> <?= $unidadeCamarao['tvpbc_id'] ?> </td>
                            <td name="inputEspecie"> <?= $unidadeCamarao['esp_nome_comum'] ?> </td>
                            <td name="inputSexo"> <?= $unidadeCamarao['tbc_sexo'] ?> </td>
                            <td name="inputMaturidade"> <?= $unidadeCamarao['tmat_tipo'] ?> </td>
                            <td name="inputComp.Cabeca"> <?= $unidadeCamarao['tbc_comprimento_cabeca'] ?> </td>
                            <td name="inputPeso"> <?= $unidadeCamarao['tbc_peso'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeleteUnidade('<?= $this->url(array("controller" => "vara-pesca", "action" => "deletebiocamarao"), null, true) ?>', '<?=$this->entrevista['vp_id']?>','<?= $unidadeCamarao['tvpbc_id'] ?>', '#base_camarao')"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
</fieldset>    
</form>
    <br/> <br/>
    <a href="<?= $this->url(array("controller" => "ficha-diaria", "action" => "editar","id" => $this->monitoramento['fd_id']), null, true) ?>" id="botao-ancora">Voltar à Ficha-Diária</a>
    
</div>