<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="5%">Id Entrevista</th>
            <th width="50%">Pesqueiro</th>
            <th width="30%">Tempo até o Pesqueiro</th>
            <th width="30%">Distância até o Pesqueiro</th>
            </tr>
            <?php
            foreach ($this->vVaraPesca as $key => $vVarapesca):
                ?>
                <tr id="itemVaraPescaRows">
                <td name="inputIdEntrevista"> <?= $vVarapesca['vp_id'] ?> </td>
                <td name="inputPesqueiro" > <?= $vVarapesca['paf_pesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vVarapesca['t_tempoapesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vVarapesca['t_distapesqueiro'] ?> </td>
                <td><input type="button" class="button-del" width="5%" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['vp_id'] ?>, '<?= $this->url(array("controller" => "vara-pesca", "action" => "deletepesqueiro"), null, true) ?>', <?= $vVarapesca['vp_paf_id'] ?>, 'pesqueiro')"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>