
    <h2>Desembarque->Embarcações</h2>
<form method="post">
    <fieldset id="Desembarque"></fieldset>
 
    <a id="ancora_barcos"></a>
    <fieldset class="noEditable"><legend>Embarcações:</legend>
        <fieldset class="noEditable"><legend>Adicionar Embarcações:</legend>
            <div id="base">
                <input type="button" name="Add" class="button-confirm" onclick="jsInsertDynamic(this.form, '<?= $this->url(array("controller" => "barcos", "action" => "insert"), null, true) ?>', '<?= $this->url(array("controller" => "barcos", "action" => "update"), null, true) ?>')">
                <input type="button" name="Reload" class="button-clear" onclick="jsReloadDynamic(this.form)">

                <input type="text" name="input_valor" placeholder="Embarcação" size="40"  />
                <input readonly="" type="text" name="input_id" />
            </div>
        </fieldset>
        <br>

        <table id="tblPerfil">
            <tr>
                <th width="15%">ID </th>
                <th width="65%">Conservação</th>
                <th width="5%"></th>
                <th width="5%"></th>
                <th width="5%"></th>
            </tr>
            <?php foreach ($this->barcos as $key => $dados): ?>
                <tr id="rowNumPeril<?= $key ?>">
                    <td><?= $dados['bar_id'] ?></td>
                    <td><?= $dados['bar_nome'] ?></td>
                    <td><input type="button" class="button-edit" width="5%" onclick="jsUpdateDynamic('<?= $dados['bar_id'] ?>', '<?= $dados['bar_nome'] ?>', this.form)"></td>
                    <td><input type="button" class="button-del" width="5%" onclick="jsDeleteDynamic(<?= $dados['bar_id'] ?>, '<?= $this->url(array("controller" => "barcos", "action" => "delete"), null, true) ?>')"></td>
                    <td><a id="botao-ancora" href="<?=$this->url(array("controller"=>"barcos","action"=>"novo", "id" => $dados['bar_id'] ),null,true)?>">Cadastro </a>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
    <fieldset class="noBorder">
        <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
        <a href="<?= $this->url(array("controller" => "barcos", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório - Lista</a>
    </fieldset>
</form>