
    <h2>Desembarque->Embarcações</h2>
    

<form method="post" id="barcos">
    <fieldset id="Desembarque"></fieldset>
 
    <a id="ancora_barcos"></a>
    <fieldset class="noEditable"><legend>Embarcações:</legend>
        <fieldset class="noEditable"><legend>Adicionar Embarcações:</legend>
            <div id="base">
                <input type="button" name="Add" class="busca" value="Adicionar" onclick="jsInsertDynamic(this.form, '<?= $this->url(array("controller" => "barcos", "action" => "insert"), null, true) ?>', '<?= $this->url(array("controller" => "barcos", "action" => "update"), null, true) ?>')">
                <input type="button" name="Reload" class="busca" value="Limpar campos" onclick="jsReloadDynamic(this.form)">

                <input type="text" name="input_valor" placeholder="Embarcação" size="40"  />
                <input readonly="" type="text" name="input_id" />
            </div>
        </fieldset>
        <br>

        <table id="tblPerfil" class="display" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th colspan="1">ID </th>
                <th colspan="1">Nome do barco</th>
                <th colspan="1"></th>
                <th colspan="1"></th>
                <th colspan="1"></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->barcos as $key => $dados): ?>
                <tr id="rowNumPeril<?= $key ?>">
                    <td><?= $dados['bar_id'] ?></td>
                    <td><?= $dados['bar_nome'] ?></td>
                    <td><a id="botao-ancora" href="<?=$this->url(array("controller"=>"barcos","action"=>"novo", "id" => $dados['bar_id'] ),null,true)?>">Cadastro</a></td>
                    <td>
                        <a onclick="jsUpdateDynamic('<?= $dados['bar_id'] ?>', '<?= $dados['bar_nome'] ?>', document.getElementById('barcos'))">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                            </ul>
                        </a>
                    </td>
                    <td>
                        <a onclick="jsDeleteDynamic(<?= $dados['bar_id'] ?>, '<?= $this->url(array("controller" => "barcos", "action" => "delete"), null, true) ?>')">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                            </ul>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="noBorder">
        
        <a href="<?= $this->url(array("controller" => "barcos", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório - Lista</a>
    </fieldset>
</form>