<div id="tablebarcos">
    <table>
        <tr>
        <th>Arte de Pesca </th>
        <th>Barco</th>
        <th>Tipo de Barco</th>
        <th>Pescador</th>
        <th>Apelido</th>
        <th>Porto</th>
        </tr>

        <?php foreach ($this->arrayBarArrasto as $key => $entrevista): ?>
            <tr>
            <td>Arrasto de Fundo</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                        <a href="<?= $this->url(array("controller" => "arrasto-fundo", "action" => "editar", "id" => $entrevista['af_id']), null, true) ?>">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                            </ul>
                        </a>
                    </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarCalao as $key => $entrevista): ?>
            <tr>
            <td>Calão</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "calao", "action" => "editar", "id" => $entrevista['cal_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


        <?php foreach ($this->arrayBarColeta as $key => $entrevista): ?>
            <tr>
            <td>Coleta Manual</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "coleta-manual", "action" => "editar", "id" => $entrevista['cml_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarEmalhe as $key => $entrevista): ?>
            <tr>
            <td>Emalhe</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "emalhe", "action" => "editar", "id" => $entrevista['em_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarGrosseira as $key => $entrevista): ?>
            <tr>
            <td>Groseira/Espinhel</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "grosseira", "action" => "editar", "id" => $entrevista['grs_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarJerere as $key => $entrevista): ?>
            <tr>
            <td>Jerere</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "jerere", "action" => "editar", "id" => $entrevista['jre_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarLinha as $key => $entrevista): ?>
            <tr>
            <td>Pesca de Linha</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "linha", "action" => "editar", "id" => $entrevista['lin_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarLinhaFundo as $key => $entrevista): ?>
            <tr>
            <td>Linha de Fundo</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "linha-fundo", "action" => "editar", "id" => $entrevista['lf_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarManzua as $key => $entrevista): ?>
            <tr>
            <td>Manzua</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "manzua", "action" => "editar", "id" => $entrevista['man_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


        <?php foreach ($this->arrayBarMergulho as $key => $entrevista): ?>
            <tr>
            <td>Mergulho</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "mergulho", "action" => "editar", "id" => $entrevista['mer_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarRatoeira as $key => $entrevista): ?>
            <tr>
            <td>Ratoeira</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "ratoeira", "action" => "editar", "id" => $entrevista['rat_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


        <?php foreach ($this->arrayBarSiripoia as $key => $entrevista): ?>
            <tr>
            <td>Siripoia</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "siripoia", "action" => "editar", "id" => $entrevista['sir_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarTarrafa as $key => $entrevista): ?>
            <tr>
            <td>Tarrafa</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "tarrafa", "action" => "editar", "id" => $entrevista['tar_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBarVaraPesca as $key => $entrevista): ?>
            <tr>
            <td>Vara de Pesca</td>
            <td><?= $entrevista['bar_nome'] ?></td>
            <td><?= $entrevista['tte_tipoembarcacao'] ?></td>
            <td><?= $entrevista['tp_nome'] ?></td>
            <td><?= $entrevista['tp_apelido'] ?></td>
            <td><?= $entrevista['pto_nome'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "vara-pesca", "action" => "editar", "id" => $entrevista['vp_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


    </table>
</div>