<h2>Monitoramento</h2>
<p>
O programa de Monitoramento da Atividade Pesqueira tem como objetivo implementar o sistema de monitoramento pesqueiro junto aos pescadores das comunidades costeiras e estuarinas a serem potencialmente afetadas pelo empreendimento Porto Sul para coleta e análise de dados sobre a atividade de pesca artesanal de forma a se avaliar a ocorrência e a magnitude de impactos ao setor. A proposta é composta por quatro linhas de ações. 
</p>
<p>
A linha de ação Perfil Social visa caracterizar socialmente e economicamente os executores das atividades pesqueiras. Serão priorizadas metodologias participativas para entender como está a situação dos praticantes da pesca na região. A linha de ação Tráfego de Embarcações tem por finalidade monitorar as embarcações que efetivamente utilizam as áreas de influência do Porto Sul, bem como a presença de cetáceos e tartarugas-marinhas na área de trânsito das embarcações. 
O monitoramento ocorre por meio de uma lancha, sobre um Grid, devidamente projetado, em sua respectiva área de abrangência. 
A linha de ação Controle de Desembarque irá determinar, por meio de monitoramento participativo, de que forma é realizada a pesca, a quantidade de embarcações, os tipos de pescado, a produção pesqueira e a Captura por Unidade de Esforço (CPUE), o valor dos pescados e como está a atual cadeia comercial da pesca. 
Por fim, a linha de ação Banco de Dados integrará todas as variáveis coletadas e possibilitará a compreensão da dinâmica pesqueira local.
</p>