<div id="titulos">
    <h2>Perfil Social->Tipo de Embarcação</h2>
    <h3>Editar</h3>
</div>



<form id="tipo-embarcacao" action="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"atualizar"),null,true)?>" method="post">
    <fieldset id="dadosSocial">
        <div class="esquerda">
            <input type="hidden" name="idtipoembarcacao" value="<?=$this->tipoEmbarcacao['tte_id']?>" />
            <div class="form-esq">
                <label for="tipoEmbarcacao">Tipo de Embarcação</label>
                <input type="text" name="tipoEmbarcacao" id="tipoEmbarcacao" placeholder="Tipo de Embarcação" value="<?=$this->tipoEmbarcacao['tte_tipoembarcacao']?>"/>
            </div>
            
            <div class="Submit">
            <a href="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a> 
            <input type="submit" value="Atualizar" />
        </div>
        </div>
    </fieldset>
</form>