
<div id="titulos">
    <h2>Desembarque->Amostragem de Camarão</h2>
    <h3>Editar</h3>
</div>


<form id="formulario" action="<?= $this->url(array("controller" => "amostra-camarao", "action" => "atualizar"), null, true) ?>" method="post">
    <fieldset id="Desembarque">
        <div class="esquerda">
            <div class="form-esq">
                <label for="id">ID:</label>
                <input type="text" name="id_amostra" placeholder="Id" id="id_ficha" value="<?= $this->amostragem['tamc_id']?>" disabled/><br />
            </div>

            <div class="form-esq">
                <label for="tipo">Estagiário:</label>
                <select name="select_nome_estagiario" >

                    <option nome="nome_estagiario" value="<?= $this->usuario['tu_id'] ?>"><?= $this->usuario['tu_nome'] ?></option>


                </select></br>
            </div>

            <div class="form-esq">
                <label for="tipo">Monitor:</label>
                <select name="select_nome_monitor" >
                    <?php
                    foreach ($this->users as $key => $monitor):
                        ?>

                        <option nome="nome_monitor" value="<?= $monitor['tu_id'] ?>" <?= ($monitor['tu_id'] == $this->amostragem['tu_id_monitor']) ? 'selected="selected"' : ''?>><?= $monitor['tu_nome'] ?></option>

                        <?php
                    endforeach;
                    ?>
                </select></br>
            </div>

            <div class="form-esq">
                <label for="tipo">Data:</label>
                <input type="date"  placeholder="Data" name="data_amostra" value="<?= $this->amostragem['tamc_data']?>"/><br />
            </div>


            <div class="form-esq">  
                <label for="tipo">Porto:</label>
                <select name="select_nome_porto" >
                    <?php
                    foreach ($this->dados_porto as $key => $porto):
                        ?>

                        <option nome="nome_porto" value="<?= $porto['pto_id'] ?>" <?= ($porto['pto_id'] == $this->amostragem['pto_id']) ? 'selected="selected"' : ''?>><?= $porto['pto_nome'] ?></option>

                        <?php
                    endforeach;
                    ?>
                </select></br>
            </div>   
            <div class="form-esq">
                <label>Barco:</label>
                <select name="nomeBarco" placeholder="Nome do Barco" />
                <?php
                foreach ($this->barcos as $key => $barco):
                    ?>
                    <option value="<?= $barco['bar_id'] ?>" <?= ($barco['bar_id'] == $this->amostragem['bar_id']) ? 'selected="selected"' : ''?>><?= $barco['bar_nome'] ?></option>
                    <?php
                endforeach;
                ?>
                </select>
                <br />
            </div>
            <div class="form-esq">
                <label>Pesqueiro:</label>
                <select name="nomePesqueiro">
                    <?php foreach ($this->pesqueiros as $key => $pesqueiro): ?>
                        <option value="<?= $pesqueiro['paf_id']; ?>"<?= ($pesqueiro['paf_id'] == $this->amostragem['paf_id']) ? 'selected="selected"' : ''?>><?= $pesqueiro['paf_pesqueiro']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-esq">
                <label>Espécie Capturada:</label>
                <select name="especie_camarao">
                    <?php foreach ($this->especies as $key => $especie): ?>
                        <option value="<?= $especie['esp_id']; ?>" <?= ($especie['esp_id'] == $this->amostragem['esp_id']) ? 'selected="selected"' : ''?>><?= $especie['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-esq">
                <label for="tipo">Captura total:</label>
                <input type="text"  placeholder="Captura Total" name="captura_total" value="<?= $this->amostragem['tamc_captura_total']?>"/><br />
            </div>
            <div class="form-esq">
                <label for="tipo">Id Subamostra:</label>
                <select name="subamostra_id"/>
                    <?php foreach ($this->subamostras as $key => $subamostra): ?>
                        <option value="<?= $subamostra['sa_id']; ?>" <?= ($subamostra['sa_id'] == $this->amostragem['sa_id']) ? 'selected="selected"' : ''?>><?= $subamostra['tp_nome'].'-'.$subamostra['sa_id']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <input type="hidden" name="id_amostra" value="<?= $this->amostragem['tamc_id']?>"/><br />
            
            <div class="Submit">
                <input type="submit" value="Salvar Alterações" /> 
            </div>
          
                    
            
        </div>
        <br/>
    </fieldset>
</form>
<form>
  <fieldset class="noEditable"><legend>Amostras de Camarão:</legend>
        <fieldset class="noEditable"><legend>Dados das Amostras:</legend>

            <div id="base">
                <input onclick="jsInsertAmostraCamarao(this.form, '<?= $this->url(array("controller" => "amostra-camarao", "action" => "insertunidade"), null, true) ?>','<?=$this->amostragem['tamc_id']?>')" type="button" value="Adicionar" />
                
                <select style="float:left;" name="SelectEspecie">
                    <?php foreach ($this->especies as $key => $especieCamarao): ?>
                        <option value="<?= $especieCamarao['esp_id']; ?>"><?= $especieCamarao['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <select style="float:left;" class="amostragem" name="SelectSexo" style="width:5px">
                    <option value="M">Macho</option>
                    <option value="F">Fêmea</option>
                    <option value="I">Indefinido</option>
                </select>
                <select style="float:left;" class="amostragem" name="SelectMaturidade">
                    <?php foreach ($this->maturidade as $key => $maturidade): ?>
                        <option value="<?= $maturidade['tmat_id']; ?>"><?= $maturidade['tmat_tipo']; ?></option>
                    <?php endforeach; ?>
                </select>
                
                <input style="float:left;" type="text" name="comprimentoCabeca" placeholder="Comp. Carapaça" size="10px">

                <input style="float:left;" type="text" name="peso" placeholder="Peso" size="10px">

                <input type="hidden" name="id_amostragem"  value="<?= $this->entrevista['af_id'] ?>"/>

            </div>

        </fieldset>
        <br>
         <fieldset class="noEditable" id="itemArteTipoRows"><legend>Dados Cadastrados:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        
                        <th width="20%">Id Amostra</th>
                        <th width="10%">Sexo</th>
                        <th width="20%">Maturidade</th>
                        <th width="20%">Comp.Carapaça</th>
                        <th width="20%">Peso</th>
                    </tr>
                    <?php
                    foreach ($this->unidadeCamarao as $key => $unidadeCamarao):
                        ?>
                        <tr id="itemEmbarcacoesRows">
                            
                            <td name="inputAmostra"> <?= $unidadeCamarao['tuc_id'] ?> </td>
                            <td name="inputSexo"> <?= $unidadeCamarao['tuc_sexo'] ?> </td>
                            <td name="inputMaturidade"> <?= $unidadeCamarao['tmat_tipo'] ?> </td>
                            <td name="inputComp.Cabeca"> <?= $unidadeCamarao['tuc_comprimento_cabeca'] ?> </td>
                            <td name="inputPeso"> <?= $unidadeCamarao['tuc_peso'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeleteUnidade(<?= $this->amostragem['tamc_id'] ?>, '<?= $this->url(array("controller" => "amostra-camarao", "action" => "deleteunidade"), null, true) ?>', <?= $unidadeCamarao['tuc_id'] ?>)"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
</fieldset>
</form>
<div class="Submit">
    <a href="<?= $this->url(array("controller" => "amostra-camarao", "action" => "index"), null, true) ?>" id="botao-ancora">Voltar</a>           
</div>  