

    <h2>Perfil Social->Escolaridade</h2>

    <a href="<?= $this->url(array("controller" => "escolaridade", "action" => "novo"), null, true) ?>" id="botao-ancora">Novo</a>
    <fieldset id="dadosSocial"></fieldset>
    <table>
        <tr>
            <th>ID</th>
            <th>Programa Social</th>
        </tr>

        <?php foreach ($this->escolaridades as $key => $escolaridade): ?>
            <tr>
                <td><?= $escolaridade['esc_id'] ?></td>
                <td><?= $escolaridade['esc_nivel'] ?></td>

                <td class="td-botao">
                    <a href="<?= $this->url(array("controller" => "escolaridade", "action" => "editar", "id" => $escolaridade['esc_id']), null, true) ?>">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a>
                </td>

                <td class="td-botao">
                    <a value="Excluir" onclick="beforeDelete('<?= $this->url(array("controller" => "escolaridade", "action" => "excluir", "id" => $escolaridade['esc_id']), null, true) ?>')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                    
                </td>

            </tr>
        <?php endforeach; ?>
    </table>
    <br/><br/>
    <a href="<?= $this->url(array("controller" => "escolaridade", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
