<div id="tipoDependnete">
    <h2>Perfil Social -> Tipo Dependente</h2>
    <h3>Novo</h3>
</div>

<form action="<?= $this->url(array("controller" => "tipo-dependente", "action" => "criar"), null, true) ?>" method="post">
    <fieldset id="dadosSocial" name="novoTipoDependente">
        <div class="esquerda">

            <div class="form-esq"> 
                <label>Código: </label>
                <input type="text" readonly="" size="5" name="idTipoDependente" placeholder="Código Dependente (Automático)"/>
            </div>

            <div class="form-esq"> 
                <label>Dependente: </label>
                <input type="text" required=""  name="tipoDependente" placeholder="Tipo Dependente"/> <br />
            </div>

            <div class="Submit">
                <a href="<?= $this->url(array("controller" => "tipo-dependente", "action" => "index"), null, true) ?>" id="botao-ancora">Voltar</a>
                <input type="submit" value="Cadastrar" />
            </div>
        </div>   
    </fieldset>
</form>
