<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="15%">Id Entrevista</th>
            <th width="85%">Pesqueiro</th>
            </tr>
            <?php
            foreach ($this->vTarrafa as $key => $vTarrafa):
                ?>
                <tr id="itemTarrafaRows">
                <td name="inputIdEntrevista"> <?= $vTarrafa['tar_id'] ?> </td>
                <td name="inputPesqueiro"> <?= $vTarrafa['paf_pesqueiro'] ?> </td>
                <td class="td-botao">
                    <a name="Editar" class="button-del" onclick="ajax_update_pesqueiro('<?= $vTarrafa['tar_paf_id'] ?>','<?= $vTarrafa['paf_id'] ?>', '', '', document.getElementById('formEntrevistas'))">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a>
                </td>
                <td class="td-botao">
                    <a name="Excluir" class="button-del" onclick="ajax_delete_entrevista_has(<?= $this->entrevista['tar_id'] ?>, '<?= $this->url(array("controller" => "tarrafa", "action" => "deletepesqueiro"), null, true) ?>', <?= $vTarrafa['tar_paf_id'] ?>, 'pesqueiro')">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a> 
                </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>