<div id="pesqueiro">
    <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
        <table id="pesqueiros">
            <tr>
            <th width="5%">Id Entrevista</th>
            <th width="50%">Pesqueiro</th>
            <th width="30%">Tempo até o Pesqueiro</th>
            <th width="30%">Distância até o Pesqueiro</th>
            </tr>
            <?php
            foreach ($this->vMergulho as $key => $vMergulho):
                ?>
                <tr id="itemMergulhoRows">
                <td name="inputIdEntrevista"> <?= $vMergulho['mer_id'] ?> </td>
                <td name="inputPesqueiro" > <?= $vMergulho['paf_pesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vMergulho['t_tempoapesqueiro'] ?> </td>
                <td name="inputTempoaPesqueiro"> <?= $vMergulho['t_distapesqueiro'] ?> </td>
                <td><input type="button" class="button-del" width="5%" onclick="jsDeletePesqueiro(<?= $this->entrevista['mer_id'] ?>, '<?= $this->url(array("controller" => "mergulho", "action" => "deletepesqueiro"), null, true) ?>', <?= $vMergulho['mer_paf_id'] ?>)"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>