<h2>Relatórios Estatísticos - Entrevistas Realizadas</h2>

<a href="<?= $this->url(array("controller" => "estatistica", "action" => "index"), null, true) ?>" id="botao-ancora">Voltar</a><br/><br/>

<script src="js/Chart.min.js"></script>
<p> Quantidade total de Entrevistas Realizadas: <b><?=$this->totalEntrevistas ?></b> </p>

<script type="text/javascript">
    
    var azulClaro = "rgba(89,130,149,.8)";
    var azulEscuro = "rgba(38,60,91,1)";
    var azul = "rgba(0,0,255,1)";
    var vermelhoClaro = "rgba(217,86,104,.8)";
    var vermelhoEscuro = "rgba(144,36,36,1)";
    var vermelho = "rgba(255,0,0,1)";
    var verde = "rgba(0,180,0,1)";
    var verdeClaro = "rgba(153,222,157,1)";
    var verdeEscuro = "rgba(32,94,36,1)";
    var marromRachy = "rgba(95,48,43,.8)";
    var marromEscuroRachy = "rgba(68,37,33,1)";
    var laranja = "rgba(255,122,4,.5)";
    var laranjaEscuro = "rgba(255,122,12,1);";
    var azulCeleste = "rgba(102,113,199,1)";
    var azulCelesteClaro = "rgba(102,113,199,1)";
    var cinza = "rgba(205,205,205,1)";
    var cinzaEscuro = "rgba(168,168,168,1)";
    
    var options = {
        responsive:true,
        scaleOverride: false,
        animation: false
    };

    var responsive_false = {
        responsive:false
    };
    var quantidadeByArte = {
       labels: <?= $this->arrayLabels ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->arrayQuantidades ?>
           }
       ]
   };
   
   
   var pesqueirosByArrasto = {
       labels: <?= $this->pesqArrasto ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantArrasto ?>
           }
       ]
   };
   var pesqueirosByCalao = {
       labels: <?= $this->pesqCalao ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantCalao ?>
           }
       ]
   };
   var pesqueirosByColeta = {
       labels: <?= $this->pesqColeta ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantColeta ?>
           }
       ]
   };
   var pesqueirosByEmalhe = {
       labels: <?= $this->pesqEmalhe ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantEmalhe ?>
           }
       ]
   };
   var pesqueirosByGrosseira = {
       labels: <?= $this->pesqGrosseira ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantGrosseira ?>
           }
       ]
   };
   var pesqueirosByJerere = {
       labels: <?= $this->pesqJerere ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantJerere ?>
           }
       ]
   };
   var pesqueirosByLinha = {
       labels: <?= $this->pesqLinha ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantLinha ?>
           }
       ]
   };
   var pesqueirosByLinhaFundo = {
       labels: <?= $this->pesqLinhaFundo ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantLinhaFundo ?>
           }
       ]
   };
   var pesqueirosByManzua = {
       labels: <?= $this->pesqManzua ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantManzua ?>
           }
       ]
   };
   var pesqueirosByMergulho = {
       labels: <?= $this->pesqMergulho ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantMergulho ?>
           }
       ]
   };
   var pesqueirosByRatoeira = {
       labels: <?= $this->pesqRatoeira ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantRatoeira ?>
           }
       ]
   };
   var pesqueirosBySiripoia = {
       labels: <?= $this->pesqSiripoia ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantSiripoia ?>
           }
       ]
   };
   var pesqueirosByTarrafa = {
       labels: <?= $this->pesqTarrafa ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantTarrafa ?>
           }
       ]
   };
   var pesqueirosByVaraPesca = {
       labels: <?= $this->pesqVaraPesca ?>,
       datasets: [
           {
               label: "Quantidade de Embarcações Por Porto",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->quantVaraPesca ?>
           }
       ]
   };
   window.onload = function(){
        var id_barcos = document.getElementById("entrByArte").getContext("2d");
        var GenChart = new Chart(id_barcos).Bar(quantidadeByArte, options);
        
        var id_barcos = document.getElementById("pesqByArrasto").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByArrasto, options);
       
        var id_barcos = document.getElementById("pesqByCalao").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByCalao, options);
        
        var id_barcos = document.getElementById("pesqByColeta").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByColeta, options);
        
        var id_barcos = document.getElementById("pesqByEmalhe").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByEmalhe, options);
        
        var id_barcos = document.getElementById("pesqByGrosseira").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByGrosseira, options);
        
        var id_barcos = document.getElementById("pesqByJerere").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByJerere, options);
        
        var id_barcos = document.getElementById("pesqByLinha").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByLinha, options);
        
        var id_barcos = document.getElementById("pesqByLinhaFundo").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByLinhaFundo, options);
        
        var id_barcos = document.getElementById("pesqByManzua").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByManzua, options);
        
        var id_barcos = document.getElementById("pesqByMergulho").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByMergulho, options);
        
        var id_barcos = document.getElementById("pesqByRatoeira").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByRatoeira, options);
        
        var id_barcos = document.getElementById("pesqBySiripoia").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosBySiripoia, options);
        
        var id_barcos = document.getElementById("pesqByTarrafa").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByTarrafa, options);
        
        var id_barcos = document.getElementById("pesqByVaraPesca").getContext("2d");
        var GenChartA = new Chart(id_barcos).Bar(pesqueirosByVaraPesca, options);
        
    };
    
</script>

<br/>
<div class="box-chart">
    <legend>Gráfico 1: Quantidade de Entrevistas Por Arte</legend>
  <canvas id="entrByArte" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 2: Pesqueiros Mais Monitorados Em Arrasto de Fundo</legend>
  <canvas id="pesqByArrasto" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 3: Pesqueiros Mais Monitorados Em Calão</legend>
  <canvas id="pesqByCalao" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 4: Pesqueiros Mais Monitorados Em Coleta Manual</legend>
  <canvas id="pesqByColeta" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 5: Pesqueiros Mais Monitorados Em Emalhe</legend>
  <canvas id="pesqByEmalhe" style="width:100%;"></canvas>
</div>
<br/>
<br/>
<div class="box-chart">
    <legend>Gráfico 6: Pesqueiros Mais Monitorados Em Espinhel/Groseira</legend>
  <canvas id="pesqByGrosseira" style="width:100%;"></canvas>
</div>
<br/>
<br/>
<div class="box-chart">
    <legend>Gráfico 7: Pesqueiros Mais Monitorados Em Jereré</legend>
  <canvas id="pesqByJerere" style="width:100%;"></canvas>
</div>
<br/>
<br/>
<div class="box-chart">
    <legend>Gráfico 8: Pesqueiros Mais Monitorados Em Pesca de Linha</legend>
  <canvas id="pesqByLinha" style="width:100%;"></canvas>
</div>
<br/>
<br/>
<div class="box-chart">
    <legend>Gráfico 9: Pesqueiros Mais Monitorados Em Linha de Fundo</legend>
  <canvas id="pesqByLinhaFundo" style="width:100%;"></canvas>
</div>
<br/>
<br/>
<div class="box-chart">
    <legend>Gráfico 10: Pesqueiros Mais Monitorados Em Manzuá</legend>
  <canvas id="pesqByManzua" style="width:100%;"></canvas>
</div>
<br/>
<br/>
<div class="box-chart">
    <legend>Gráfico 11: Pesqueiros Mais Monitorados Em Mergulho</legend>
  <canvas id="pesqByMergulho" style="width:100%;"></canvas>
</div>
<br/>
<br/>
<div class="box-chart">
    <legend>Gráfico 12: Pesqueiros Mais Monitorados Em Ratoeira</legend>
  <canvas id="pesqByRatoeira" style="width:100%;"></canvas>
</div>
<br/>
<br/>
<div class="box-chart">
    <legend>Gráfico 13: Pesqueiros Mais Monitorados Em Siripoia</legend>
  <canvas id="pesqBySiripoia" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 14: Pesqueiros Mais Monitorados Em Tarrafa</legend>
  <canvas id="pesqByTarrafa" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 15: Pesqueiros Mais Monitorados Em Vara de Pesca</legend>
  <canvas id="pesqByVaraPesca" style="width:100%;"></canvas>
</div>
<br/>