<div id="titulos">
    <h2>Relatórios->Estatísticos</h2>
</div>
<a class="relatorio" href="<?= $this->url(array("controller" => "estatistica", "action" => "pescador"), null, true) ?>">Pescadores</a><br/>
<a class="relatorio" href="<?= $this->url(array("controller" => "estatistica", "action" => "unidadecaptura"), null, true) ?>">Unidade de Captura</a><br/>
<a class="relatorio" href="<?= $this->url(array("controller" => "estatistica", "action" => "barco"), null, true) ?>">Embarcações</a><br/>
<a class="relatorio" href="<?= $this->url(array("controller" => "estatistica", "action" => "entrevista"), null, true) ?>">Artes de Pesca - Entrevistas</a><br/>
<a class="relatorio" href="<?= $this->url(array("controller" => "estatistica", "action" => "captura"), null, true) ?>">Captura</a><br/>
<a class="relatorio" href="<?= $this->url(array("controller" => "estatistica", "action" => "avistamento"), null, true) ?>">Avistamentos</a><br/>
<a class="relatorio" href="<?= $this->url(array("controller" => "estatistica", "action" => "indexbiometrias"), null, true) ?>">Biometrias</a><br/>
