<div id="titulos">
    <h2>Biometrias</h2>
</div>
<form action="<?= $this->url(array("controller" => "estatistica", "action" => "gerar", "especie" => "camarao"), null, true) ?>">
    <div class="esquerda">
    <fieldset>
        <legend>Espécies de Camarão:</legend>
            <div class="form-esq">
                <label>Relatório Gráfico:</label>
                <select name="biometria" required>
                    <option value="" selected></option>
                    <?php foreach($this->especiesCamarao as $especie):?>
                        <option value="<?=$especie['esp_id']?>"><?=$especie['esp_nome_comum']?></option>
                    <?php endforeach;?>

                </select>
            </div>

            <div class="form-esq">     
                <input type="submit" value="Relatório"/>
            </div>
    </fieldset>
    </div>
</form>
<form action="<?= $this->url(array("controller" => "estatistica", "action" => "gerar", "especie" => "peixe"), null, true) ?>">
    <div class="esquerda">
    <fieldset>
        <legend>Espécies de Peixes:</legend>
            <div class="form-esq">
                <label>Relatório Gráfico:</label>
                <select name="biometria" required>
                    <option value="" selected></option>
                    <?php foreach($this->especiesPeixes as $especie):?>
                        <option value="<?=$especie['esp_id']?>"><?=$especie['esp_nome_comum']?></option>
                    <?php endforeach;?>

                </select>
            </div>

            <div class="form-esq">     
                <input type="submit" value="Relatório"/>
            </div>
    </fieldset>
    
    </div>
</form> 