<div id="titulos">
    <h2>Biometrias</h2>
</div>
 <a href="<?= $this->url(array("controller" => "index-admin", "action" => "index"), null, true) ?>" id="botao-ancora">Voltar</a><br/><br/>
       
<div id="esquerda_base">
        <form>
            <label>Buscar Biometrias da Espécie: </label>
            <input class="responsivo" onclick="ajax_busca_esp_capturada(this.form, '<?= $this->url(array("controller" => "estatistica", "action" => "selectespecies"), null, true) ?>')" type="button" value="Buscar Entrevistas"/>
            
            <select class="responsivo"  name="nome_comum">
                <?php foreach ($this->especiesPeixesCamarao as $key => $especie): ?>
                    <option value="<?= $especie['esp_id']; ?>" ><?= $especie['esp_nome_comum']; ?></option>
                <?php endforeach; ?>
            </select>
            <br/>

        </form>
    </div>
    
    <?php include('tableesp.phtml'); ?>
    
<form action="<?= $this->url(array("controller" => "estatistica", "action" => "gerar", "especie" => "camarao"), null, true) ?>">
    <div class="esquerda">
    <fieldset>
        <legend>Espécies de Camarão:</legend>
            <div class="form-esq">
                <label>Relatório Gráfico:</label>
                <select name="biometria" required>
                    <option value="" selected></option>
                    <?php foreach($this->especiesCamarao as $especie):?>
                        <option value="<?=$especie['esp_id']?>"><?=$especie['esp_nome_comum']?></option>
                    <?php endforeach;?>

                </select>
            </div>

            <div class="form-esq">     
                <input type="submit" value="Relatório"/>
            </div>
    </fieldset>
    </div>
</form>
<form action="<?= $this->url(array("controller" => "estatistica", "action" => "gerar", "especie" => "peixe"), null, true) ?>">
    <div class="esquerda">
    <fieldset>
        <legend>Espécies de Peixes:</legend>
            <div class="form-esq">
                <label>Relatório Gráfico:</label>
                <select name="biometria" required>
                    <option value="" selected></option>
                    <?php foreach($this->especiesPeixes as $especie):?>
                        <option value="<?=$especie['esp_id']?>"><?=$especie['esp_nome_comum']?></option>
                    <?php endforeach;?>

                </select>
            </div>

            <div class="form-esq">     
                <input type="submit" value="Relatório"/>
            </div>
    </fieldset>
    
    </div>
</form> 