<h2>Relatórios Estatísticos - Pescadores Cadastrados</h2>

<script src="js/Chart.min.js"></script>
<p> Quantidade total de Pescadores cadastrados: <b><?=$this->quantPescadores ?></b> </p>
<script type="text/javascript">

    var options = {
        responsive:true,
        scaleOverride: false,
        animation: false
    };

    var responsive_false = {
        responsive:false
    };
 
        var azulClaro = "rgba(89,130,149,.8)";
        var azulEscuro = "rgba(38,60,91,1)";
        var azul = "rgba(0,0,255,1)";
        var vermelhoClaro = "rgba(217,86,104,.8)";
        var vermelhoEscuro = "rgba(144,36,36,1)";
        var vermelho = "rgba(255,0,0,1)";
        var verde = "rgba(0,180,0,1)";
        var verdeClaro = "rgba(153,222,157,1)";
        var verdeEscuro = "rgba(32,94,36,1)";
        var marromRachy = "rgba(95,48,43,.8)";
        var marromEscuroRachy = "rgba(68,37,33,1)";
        var laranja = "rgba(255,122,4,.5)";
        var laranjaEscuro = "rgba(255,122,12,1);";
        var azulCeleste = "rgba(102,113,199,1)";
        var azulCelesteClaro = "rgba(102,113,199,1)";
    var generoPescadores = [
       {
        value: <?= $this->Masculino ?>,
        color: azul,
        highlight: "#FF5A5E",
        label: "Masculino"
       },
       {
        value: <?= $this->Feminino ?>,
        color:vermelhoClaro,
        highlight: "#FF5A5E",
        label: "Feminino"
       }
   ];
   
   
   var pescadoresByComunidades = {
       labels: <?= $this->comunidades ?>,
       datasets: [
           {
               label: "Quantidade de Pescadores Por Comunidades",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->pescByComunidades ?>
           }
       ]
   };
   
   var pescadoresByColonias = {
       labels: <?= $this->colonias ?>,
       datasets: [
           {
               label: "Quantidade de Pescadores Por Comunidades",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->pescByColonias ?>
           }
       ]
   };
   
   var pescadoresByEscolaridades = {
       labels: <?= $this->escolaridades ?>,
       datasets: [
           {
               label: "Quantidade de Pescadores Por Comunidades",
               fillColor: "rgba(95,48,43,.8)",
               strokeColor: "rgba(95,48,43,1)",
               pointColor: "rgba(95,48,43,1)",
               pointStrokeColor: "#fff",
               pointHighlightFill: "#fff",
               pointHighlightStroke: "rgba(95,48,43,1)",
               data: <?= $this->pescByEscolaridade ?>
           }
       ]
   };
   window.onload = function(){
        var id_barcos = document.getElementById("genero").getContext("2d");
        var GenChart = new Chart(id_barcos).Pie(generoPescadores, responsive_false);
        
        
        var ctx = document.getElementById("pescByComunidades").getContext("2d");
        var PescByPorChartComunidade = new Chart(ctx).Bar(pescadoresByComunidades, options);
        
        var ctx = document.getElementById("pescByColonias").getContext("2d");
        var PescByPorChartColonia = new Chart(ctx).Bar(pescadoresByColonias, options);
        
        var ctx = document.getElementById("pescByEscolaridades").getContext("2d");
        var PescByPorChartEscolaridades = new Chart(ctx).Bar(pescadoresByEscolaridades, options);
    };
</script>

<br/>
<div class="box-chart">
    <legend>Gráfico 1: Quantidade Pescadores Por Gênero</legend>
  <canvas id="genero" style="width:100%;"></canvas>
</div>
<br/>


<br/>
<div class="box-chart">
    <legend>Gráfico 16: Quantidade de Pescadores por Comunidades</legend>
  <canvas id="pescByComunidades" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 17: Quantidade de Pescadores por Colônias</legend>
  <canvas id="pescByColonias" style="width:100%;"></canvas>
</div>
<br/>

<br/>
<div class="box-chart">
    <legend>Gráfico 18: Quantidade de Pescadores por Escolaridade</legend>
  <canvas id="pescByEscolaridades" style="width:100%;"></canvas>
</div>
<br/>