<div id="espcapturada">
    <table>
        <tr>
        <th>Arte de Pesca</th>
        <th>Espécie</th>
        <th>Comprimento</th>
        <th>Peso</th>
        <th>Sexo</th>
        <th>Número da Entrevista</th>
        </tr>
        <?php foreach ($this->arrayBioCamarao as $key => $entrevista): ?>
            <tr>
            <td>Arrasto de Fundo</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbc_comprimento_cabeca']." mm" ?></td>
            <td><?= $entrevista['tbc_peso']." g" ?></td>
            <td><?= $entrevista['tbc_sexo'] ?></td>
            <td><?= $entrevista['af_id'] ?></td>
            <td class="td-botao">
                        <a href="<?= $this->url(array("controller" => "arrasto-fundo", "action" => "editar", "id" => $entrevista['af_id']), null, true) ?>">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                            </ul>
                        </a>
                    </td>
            </a>
            </tr>
        <?php endforeach; ?>
        <?php foreach ($this->arrayBioArrasto as $key => $entrevista): ?>
            <tr>
            <td>Arrasto de Fundo</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['af_id'] ?></td>
            <td class="td-botao">
                        <a href="<?= $this->url(array("controller" => "arrasto-fundo", "action" => "editar", "id" => $entrevista['af_id']), null, true) ?>">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                            </ul>
                        </a>
                    </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioCalao as $key => $entrevista): ?>
            <tr>
            <td>Calão</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['cal_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "calao", "action" => "editar", "id" => $entrevista['cal_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


        <?php foreach ($this->arrayBioColetaManual as $key => $entrevista): ?>
            <tr>
            <td>Coleta Manual</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['cml_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "coleta-manual", "action" => "editar", "id" => $entrevista['cml_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioEmalhe as $key => $entrevista): ?>
            <tr>
            <td>Emalhe</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['em_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "emalhe", "action" => "editar", "id" => $entrevista['em_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioGrosseira as $key => $entrevista): ?>
            <tr>
            <td>Groseira/Espinhel</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['grs_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "grosseira", "action" => "editar", "id" => $entrevista['grs_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioJerere as $key => $entrevista): ?>
            <tr>
            <td>Jerere</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['jre_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "jerere", "action" => "editar", "id" => $entrevista['jre_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioLinha as $key => $entrevista): ?>
            <tr>
            <td>Pesca de Linha</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['lin_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "linha", "action" => "editar", "id" => $entrevista['lin_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioLinhaFundo as $key => $entrevista): ?>
            <tr>
            <td>Linha de Fundo</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['lf_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "linha-fundo", "action" => "editar", "id" => $entrevista['lf_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioManzua as $key => $entrevista): ?>
            <tr>
            <td>Manzua</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['man_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "manzua", "action" => "editar", "id" => $entrevista['man_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


        <?php foreach ($this->arrayBioMergulho as $key => $entrevista): ?>
            <tr>
            <td>Mergulho</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['mer_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "mergulho", "action" => "editar", "id" => $entrevista['mer_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioRatoeira as $key => $entrevista): ?>
            <tr>
            <td>Ratoeira</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['rat_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "ratoeira", "action" => "editar", "id" => $entrevista['rat_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


        <?php foreach ($this->arrayBioSiripoia as $key => $entrevista): ?>
            <tr>
            <td>Siripoia</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['sir_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "siripoia", "action" => "editar", "id" => $entrevista['sir_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioTarrafa as $key => $entrevista): ?>
            <tr>
            <td>Tarrafa</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['tar_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "tarrafa", "action" => "editar", "id" => $entrevista['tar_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>

        <?php foreach ($this->arrayBioVaraPesca as $key => $entrevista): ?>
            <tr>
            <td>Vara de Pesca</td>
            <td><?= $entrevista['esp_nome_comum'] ?></td>
            <td><?= $entrevista['tbp_comprimento']." cm" ?></td>
            <td><?= $entrevista['tbp_peso']." kg" ?></td>
            <td><?= $entrevista['tbp_sexo'] ?></td>
            <td><?= $entrevista['vp_id'] ?></td>
            <td class="td-botao">
                <a href="<?= $this->url(array("controller" => "vara-pesca", "action" => "editar", "id" => $entrevista['vp_id']), null, true) ?>">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                        <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                    </ul>
                </a>
            </td>
            </a>
            </tr>
        <?php endforeach; ?>


    </table>
</div>

<br/>